### ISSUE TITLE
Visual Studio Code extension

### ISSUE THREAD

**Issue by audioboxer217** [CloudSlang/cloud-slang#1025]
I'm not entirely sure if this is the correct place for this, but since the [Roadmap ](https://github.com/CloudSlang/cloud-slang/wiki/Project-Roadmap) is in the Wiki for this repo I figured it's the best option.

I would like to see an extension for Visual Studio Code similar to whats been done for Atom.  VSCode has become fairly popular recently and I'm sure it would be well used.  In case you haven't heard of it, you can find out more here. https://code.visualstudio.com/

I'd even be up for helping out if I have some available time.  I have never written an extension for vscode so it would definitely be interesting for me.

**Comment by robert-sandor** [comment]
Hello @audioboxer217,

Thank you for your input, we will look into this as soon as we can, and we'll get back to you here with an answer.
I think it would be a great idea for CloudSlang to support the major editors, but we'll see how the discussion with the owners goes.

**Comment by Bonczidai** [comment]
@audioboxer217 definitely a good idea - btw we have an extension for IntelliJ as well: https://github.com/CloudSlang/cs-intellij-plugin

**Comment by audioboxer217** [comment]
Great, thanks, guys!  I hope you are able to do this as vscode has become my go-to editor.  I did start to look into creating the extension myself and will post here if I have some time to make some progress on it.  
Just as an FYI, I've been [reading here.](https://code.visualstudio.com/docs/extensions/overview)

**Comment by audioboxer217** [comment]
I had some time to do an initial pass at this [here](https://github.com/audioboxer217/vscode-cloudslang).  It's kind of rough at the moment because it's basically just a port of the Atom plugin, but it does work.  Feel free to use it if you like.

Some of the other language extensions I've used in vscode allow for tab completion of snippets (i.e. typing "oper" would suggest the "operation" snippet and pressing tab would fill it in).  I'm not sure how this is done so what I've done here doesn't accomplish that.

**Comment by Bonczidai** [comment]
great initial step - I like it a lot 👍

**Comment by andreivasiletruta** [comment]
@audioboxer217 we forked your repo under our [organization ](https://github.com/CloudSlang/cs-vscode) and plan to continue the implementation there as discussed. great initiative!

**Comment by Bonczidai** [comment]
cool 👌 - closing this issue
