### ISSUE TITLE
Not working: run --f ../content/io/cloudslang/base/print/print_text.sl --i text=first_flow

### ISSUE THREAD

**Issue by emichaf** [CloudSlang/cloud-slang#1036]
Started CloudSlang in Docker container, and run:
run --f ../content/io/cloudslang/base/print/print_text.sl --i text=first_flow

Return error:
Command failed java.lang.RuntimeException: Failed compilation for file : print_text.sl ,Exception is : java.lang.RuntimeException: Duplicate executable found: 'io.cloudslang.base.pr
int.print_text'

**Comment by andreivasiletruta** [comment]
You will need to run it like
`run --f /usr/cslang/cslang-cli/content/io/cloudslang/base/print/print_text.sl --i text=Hi`
and it should work

**Comment by Bonczidai** [comment]
should work with [v1.0.19](https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-1.0.19)

**Comment by victornoel** [comment]
@Bonczidai it is still not working with latest docker image.

Did you notice that it means that the MAIN example on both your webpage and github repository does not work and throw an error?

**Comment by Bonczidai** [comment]
@victornoel that is most certainly a valid point - it seems to me that the CloudSlang docker image uses an old version `cloudslang-1.0.10` (based on the [Dockerfile](https://hub.docker.com/r/cloudslang/cloudslang/~/dockerfile/))

@CloudSlang/cs-lang-team @tethryus can you take a look?

**Comment by tethryus** [comment]
@Bonczidai @victornoel I will look into it and try to solve the issue.

**Comment by pendulm** [comment]
@tethryus docker image is still old version

![image](https://user-images.githubusercontent.com/282373/49629864-90cf3500-fa26-11e8-80b3-c3447dfa18ae.png)
