### ISSUE TITLE
Anyway the embedded CloudSlang can be used without Maven

### ISSUE THREAD

**Issue by ssrini** [CloudSlang/cloud-slang#1142]
I am using the CloudSlang engine in an embedded mode in a Spring Web Application.  The jars with custom actions is already in the class path.

Is there any way that the maven dependency download etc can be avoided or is that a mandatory step?

**Comment by dasom1982** [comment]
Yes, You'll probably need it.
I couldn't find anything to avoid.

**Comment by ssrini** [comment]
Yeah.  I did go through the code and its hard wired.  The only way to avoid a download while running is to already use maven to update the m2 cache with all the required jars.  Or change/customize the implementation in cloudslang ourselves
