### ISSUE TITLE
Variable number of outputs from a Java Action

### ISSUE THREAD

**Issue by srinisubramanian** [CloudSlang/cloud-slang#1220]
I have a use case where a variable list of outputs which are determined during the run of the Java action need to be published.  The names of these are determined at run time and hence cannot be added to the @Output

Is it possible to even achieve this?

**Comment by dCode91** [comment]
What if you define a single string output and create a list out of the data that you get from the Java action? Then you could parse the list and pass it to the next step.

**Comment by srinisubramanian** [comment]
Hey @dCode91 thanks for responding. Do you have a snippet for parsing to list and setting the results? That may be a good solution

**Comment by srinisubramanian** [comment]
Nevermind @dCode91 got what you were hinting at

I now return a comma separated string of values from java and in publish split using , and have mulitple values now. 

For e.g. 

- publish:
  - someval: ${result.split(",")[0]} and so on. 

Thanks
