### ISSUE TITLE
Flow/Operation namespace doesn't support foreign chars

### ISSUE THREAD

**Issue by einatneu** [CloudSlang/cloud-slang#139]
Flow/Operation namespace doesn't support foreign chars, for example: 你好

**Comment by Bonczidai** [comment]
need to check whether it was fixed with recent encoding fixes

**Comment by Bonczidai** [comment]
works after encoding enhancements in CS runtime

in builder, it the chars are limited:
```
02:50:16 [ERROR] Exception: Namespace: io.cloudslang.base.?? is invalid. It can contain only alphanu
meric characters, underscore or hyphen
```

question is whether we want to allow other chars than the ones listed here?

**Comment by Bonczidai** [comment]
for now we are staying with the current implementation - internally (under CS API) we support any unicode char, however in builder we validate the range (alphanumeric characters, underscore or hyphen, dot) since we only allow these chars in our repository folders
