### ISSUE TITLE
unstable loops tests

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#154]
The tests : 
  LoopFlowsTest.testFlowWithMapLoopsWithDefaultBreak:152 expected:<2> but was:<3>
  LoopFlowsTest.testFlowWithMapLoops:122 null
  LoopFlowsTest.testFlowWithMapLoopsWithBreak:181 expected:<3> but was:<4>

Fail locally at my machine (noth by running from maven AND from IDE)...

**Comment by meirwah** [comment]
@Bonczidai / @orius123 are you familier with this ?

**Comment by orius123** [comment]
I have sporadic failures, not related to maps loops.

**Comment by meirwah** [comment]
I get this tests fail each time... not sporadic ...

**Comment by meirwah** [comment]
Please look at this issue @Bonczidai ...

**Comment by meirwah** [comment]
Failed tests:
  LoopFlowsTest.testFlowWithMapLoopsWithDefaultBreak:164 expected:<2> but was:<3>
  LoopFlowsTest.testFlowWithMapLoops:118->verifyPersonMap:206 null
  LoopFlowsTest.testFlowWithHashMap:136->verifyPersonMap:206 null
  LoopFlowsTest.testFlowWithMapLoopsWithBreak:193 expected:<3> but was:<4>
