### ISSUE TITLE
the “fromInput” construct still seems like breaking the elegance of the language [2]

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#196]
@arjuan : 
a.	better define the scope on names (like in Java, if you define for (int param=0; param < 100; param++) then ‘param’ is known at the scope of the loop as the counter even if there’s a method input or a class member named ‘param’).
b.	Stick to the elegancy of our YAML notation and refrain from using word constructs like “fromInput”, just use some textual marker like ${param}, $param, %param% or whatever you’d like..

Hope it makes sense (?)

**Comment by oritstone** [comment]
We can use current flow name

**Comment by oritstone** [comment]
We currently have in our CloudSlang DSL an option to refer in the task's publish param or flow\operation output param to an input, using the `fromInput` keyword.
For example:
```yaml
outputs:
  - output1: fromInputs['input1']
```
Do you think that the keyword's name is not elegant.
Maybe use something like:
```yaml
outputs:
  - output1: self['input1']
```
or use the flow name. For example if the flow name is `flow1`:
```yaml
outputs:
  - output1: flow1['input1']
```
@CloudSlang/slang-functional-reviewers  WDYT?

**Comment by orius123** [comment]
:+1: for `self`

**Comment by Bonczidai** [comment]
`self`
