### ISSUE TITLE
Uninformative error message in CLI when missing spaces before 'required' keyword

### ISSUE THREAD

**Issue by einatneu** [CloudSlang/cloud-slang#199]
When there are missing spaces before input's 'required' keyword, for example:
flow:
  inputs:
    - input:
      required: true

 and trying to run the flow in the CLI, you get an uninformative error message:
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error transforming source: flow_with_required_input.sl to a Slang model. null

**Comment by meshipeer** [comment]
also raised during bug hunt by Ziso and @SSgtMendel:
missing indentations for the required/default - error not clear: "slang model - null"
 inputs:
    - targetMachine
    - username:
      required: false
      default: "'root'"

**Comment by lirantal** [comment]
I just stumbled on the same exact issue when working on a new flow, and this error message is completely uninformative and useless to the user:

```bash
[ERROR] Exception: Failed creating Slang models for file: 'lirantal-cloud-slang-content.git/test/io/cloudslang/git/test_git_flow.sl'.
Error transforming source: test_git_flow.sl to a Slang model. Task: reset_git_branch has no data
```

I was able to figure out that it's due to indentations but that is way not clear.
Can we re-open this issue and try to actually address this bug? @oritstone @orius123

**Comment by orius123** [comment]
Are you using latest RC? https://github.com/CloudSlang/cloud-slang/releases/download/cloudslang-0.8.RC1/cslang-cli-with-content.zip

**Comment by lirantal** [comment]
@orius123 you need to add a --version to cslang-builder :-)
I'm using 0.4.29
