### ISSUE TITLE
system tests framework problem

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#206]
Wrote three test cases for the run_command.sl operation from cloud-slang-content repo and noticed some odd behavior.

The testfile can be found on the system_tests branch, and is called run_command.inputs.yaml.
ATM, all tests pass. But I tried commenting the last line (throwsException: true from third test case) and for some reason I got that the second test fails as well saying that the actual result(null) is different than expected(FAILURE) but the actual result should always be FAILURE since we modified the third test.

I tried debugging it, and it worked, then I ran it again, it didn't work. Debugged and ran it one more time and it works and now I can't reproduce the error only by "luck".

**Comment by tudorlesan** [comment]
![system tests error](https://cloud.githubusercontent.com/assets/8058958/6962410/f3ffbc26-d93c-11e4-9fe3-746f90a32382.png)
Managed to catch it even thought the I changed the expected result to SUCCESS instead of FAILURE. It should be actual result FAILURE not null since I didn't change anything else

**Comment by tudorlesan** [comment]
![system_tests working](https://cloud.githubusercontent.com/assets/8058958/6962475/7c64c930-d93d-11e4-93a8-bdf0758af274.png)
Usually I get this even with all tests passing

**Comment by tudorlesan** [comment]
![really_odd_system_tests](https://cloud.githubusercontent.com/assets/8058958/6962590/865992c6-d93e-11e4-8786-f9bcf1400d12.png)
Adding another test and deliberately make it fail produces even more wierd behavior, mixing results through different testfiles. @oritstone @orius123 WDYT about this. Only one test should fail here.

**Comment by oritstone** [comment]
Closed via 2af7c51f3a71fe0132eea338645616a0a1d085bc
