### ISSUE TITLE
cslang CLI - Cant trigger string input with spaces

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#213]

**Comment by orius123** [comment]
Actually you can to need to wrap the whole inputs with " " it's mentioned in the docs

**Comment by meshipeer** [comment]
this is how it works with spring shell.
we have it documented: "To use inputs that include spaces, enclose the entire input list in quotes ("):"
with example

**Comment by tudorlesan** [comment]
@meshipeer I tested this in ubuntu with master and it doesn't work..

**Comment by meshipeer** [comment]
@tudorlesan can you please share the command you used?

**Comment by tudorlesan** [comment]
#246
