### ISSUE TITLE
compiler error - when have typo in dsl (system_prop) error not clear

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#219]
raised by 3 people during bug hunt

**Comment by meshipeer** [comment]
also relevant when using "default_value" instead of "default" for example

**Comment by tudorlesan** [comment]
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error transforming
source: ping_hosts.sl to a Slang model. For task: mail_send syntax is illegal.
key: system_prop in input: hostname is not a known property

**Comment by tudorlesan** [comment]
@oritstone are we sure this wasn't solved already? seems pretty clear to me..

**Comment by oritstone** [comment]
Already fixed
