### ISSUE TITLE
Required input can be passed as empty

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#224]
1. Have an operation with an input but no value
2. Run it and do not provide --i
Result: you are required to run it as error appears: 
Command failed java.lang.RuntimeException: Slang Error : Error running: 'fileListParser': Input with name: 'fileList' is Required, but value is empty
3. Provide input with --i but with no actual value

Expected result: just input name and no value should not make the flow continue
Actual result: flow finishes with empty required input!

**Comment by oritstone** [comment]
We decided we do not want this change. We want the flexibility of passing empty string as a valid input
