### ISSUE TITLE
inputs as list of values are not possible because of runtime error

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#225]
Have list this:

namespace: bugHunt.myProject

operation:
  name: FileListParser
  inputs:
    - fileList
  action:
    python_script: print fileList
  # outputs:
  results:
    - SUCCESS
    - FAILURE

run like this: run --f c:/Work/ProductRelated/CloudSlang/bughunt/MyProject/myOp.sl --i fileList="1,2,3"
Expected result: list is accepted
Actual result: error as:
cslang>run --f c:/Work/ProductRelated/CloudSlang/bughunt/MyProject/myOp.sl --i fileList="1,2,3"
java.lang.RuntimeException: Failed to convert 'fileList="1,2,3"' to type Map for option 'i,inputs'
Input should be in a key=value comma separated format, e.g. key1=val1,key2=val2 etc.

**Comment by orius123** [comment]
you need to escape commas:
```bash
run --f content/io/cloudslang/base/print/print_text.sl --i text=[1\,2\,3]
```

**Comment by orius123** [comment]
@meshipeer is it a reasonable solution?

**Comment by meshipeer** [comment]
i don't think its optimal. but at least we need to document it.
@orius123 don't you think?

**Comment by SamMarkowitz** [comment]
It's already in the docs:

"Commas (,) can be used as part of input values by escaping them with a backslash (\)."

I will add an example.

**Comment by orius123** [comment]
please close when docs is done
