### ISSUE TITLE
CSlang release fails

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#232]
0.00s$ sudo apt-get install python-pip && ant -f build/ant.xml
      
sudo: must be setuid root
The command "sudo apt-get install python-pip && ant -f build/ant.xml
      " failed and exited with 1 during .
Your build has been stopped.

https://travis-ci.org/CloudSlang/cloud-slang/builds/57390557

Issue seems to be in the flow...

**Comment by orius123** [comment]
http://stackoverflow.com/questions/26327197/travis-ci-sudo-must-be-setuid-root

**Comment by meirwah** [comment]
it should be part of the travis.yml file then...

**Comment by meirwah** [comment]
https://travis-ci.org/CloudSlang/cloud-slang/builds/57469627


Deploying application
/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory - build/target/cloudslang-cli/cslang-cli.zip (Errno::ENOENT)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client/releases.rb:86:in `new'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client/releases.rb:86:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:118:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:134:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/provider.rb:134:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.11/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'
failed to deploy

**Comment by orius123** [comment]
the source of the problem is in the flow
     [exec] - copy_verifier
     [exec] Running command: 'cp -r  ../cloudslang-content-verifier/target/cslang-builder target'
     [exec] cp: cannot stat `../cloudslang-content-verifier/target/cslang-builder': No such file or directory

**Comment by meirwah** [comment]
is the folder path wrong?

**Comment by orius123** [comment]
don't know..
need to run it locally and see.

**Comment by meirwah** [comment]
when i run it locally i get:
WARNING: Cannot convert build_content/build_cli_flow.sl to type Boolean.
