### ISSUE TITLE
Database name is: H2 databaseMajorVersion is: 1 MUST be removed!!

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#242]
It gets printed each time the CLI starts...

**Comment by orius123** [comment]
[here is the problem](https://github.com/CloudSlang/score/blob/2271dcaf9155a220d12359e6a87632b24ddc8641/engine/data/score-data-api/src/main/java/io/cloudslang/engine/dialects/ScoreDialectResolver.java#L31)
