### ISSUE TITLE
cloud-slang Ubuntu inputs with spaces failure

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#246]
I triggered the send_mail.sp operation on ubuntu 14.04 like:

run --f (content_path)/base/mail.send_mail.sl --i hostname=(our_smtp),port=25,from=(email),to=(email),subject=test,body="hello world"

and I get: You cannot specify option 'f' when you have also specified '' in the same command
Also, if I use body=hello, it works

**Comment by tudorlesan** [comment]
@meirwah

**Comment by orius123** [comment]
you should:
```bash
run --f (content_path)/base/mail.send_mail.sl --i "hostname=(our_smtp),port=25,from=(email),to=(email),subject=test,body=hello world"
```

**Comment by tudorlesan** [comment]
@orius123 it works like that, sorry about that. It seems counterintuitive for me though. Thanks
