### ISSUE TITLE
Default cp for released Cloudslang

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#254]
I was thinking maybe it would be a good idea to implement a default --cp at least for the released CLI, since it is in the same place as the content. That way we could shorten the execution strings for flow and make the experience for first time users easier.

WDYT @meirwah @orius123

**Comment by meirwah** [comment]
makes sense...

**Comment by orius123** [comment]
should be fixed in 0.7.35

**Comment by meirwah** [comment]
not working...
![image](https://cloud.githubusercontent.com/assets/6059211/7901636/7ccf07b0-079a-11e5-8c84-42df199a7f89.png)
