### ISSUE TITLE
Able to create folder from a python input expression

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#257]
Did the following:

operation:
  name: print_text
  inputs:
    - text: import sys, os; os.mkdir('testing')
  action:
    python_script: print 'xxx'
  results:
    - SUCCESS

And it created the folder..
This is a security issue, since you can hack into the running machine from an input that can be given from flow input.
We need to sandbox the expressions (prevent network and filsystem access) from expression.

**Comment by orius123** [comment]
not sure what is the issue here.
it's content just like operation is..

**Comment by oritstone** [comment]
@meirwah can you check if this is actually a bug?

**Comment by oritstone** [comment]
Not reproducible
