### ISSUE TITLE
System tests inexistent output message

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#269]
Checking outputs that don't exist for an operation follows with 

BUILD FAILURE
------------------------------------------------------------
CloudSlang build for repository: "C:\Workspace\slang\cloud-slang-content" failed due to failed tests.
Following 1 tests failed:

------------------------------------------------------------
Exception: null

Should there be a more meaningful message?

**Comment by tudorlesan** [comment]
Also, this is happening.

[ERROR] BUILD FAILURE
[ERROR] ------------------------------------------------------------
[ERROR] CloudSlang build for repository: "C:\Workspace\slang\cloud-slang-content" failed d
ue to failed tests.
[ERROR] Following 1 tests failed:
[ERROR] - Test case failed: testStringOccurrenceCounterBothStringsEmpty - Tests that strin
g_occurrence_counter.sl operation finishes with SUCCESS having output 1 when both strings
are empty
                For output: return_result
                Expected value: 1
                Actual value: 1

Any idea why @orius123 ?

**Comment by orius123** [comment]
because it checks equality of a string to an int.
those are two different issues

**Comment by oritstone** [comment]
@tudorlesan are you updated with the latest builder tool changes? There was a fix to the outputs check yesterday. You should update, build the builder tool & run again. Or you can use the latest release 0.7.18
Let us know if it is still an issue.

**Comment by oritstone** [comment]
@tudorlesan please open a new issue for the second one you wrote

**Comment by tudorlesan** [comment]
@oritstone the second issue I wrote(the one with the verification of outputs of different types) was solved by @orius123.  Just the first one is still open. How to reproduce:

testStringOccurrenceCounterSuccess:
  inputs:
    - string_in_which_to_search: long string inin which to search
    - string_to_find: in
    - ignore_case: true
  description: Tests that string_occurrence_counter.sl operation finishes with SUCCESS when inputs are valid
  testFlowPath: io.cloudslang.base.strings.test_string_occurrence_counter
  result: SUCCESS
  outputs:
    - inexistent_output: anyvalue

**Comment by orius123** [comment]
It still happens with this fix?

**Comment by tudorlesan** [comment]
@orius123 sorry, I assumed your fix just solves one issue. Works fine. Then this can be closed.
