### ISSUE TITLE
serialization issue back

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#278]
related to #168
@orius123 @Bonczidai 

affect:

Command failed java.lang.RuntimeException: Slang Error : Error running: 'clear_docker_dangling_images_flow'.
Error binding output: 'dangling_images_list_safe_to_delete',
Error is: Error in running script expression or variable reference, for expression: 'images_list_safe_to_delete',
Script exception is: javax.script.ScriptException: NameError: name 'images_list_safe_to_delete' is not defined in

**Comment by orius123** [comment]
Serialization of what? What version?

**Comment by meirwah** [comment]
latest slang version 1.7.20

**Comment by meirwah** [comment]
Serialization of some step inputs

**Comment by meirwah** [comment]
This is related to the fix you PR Jython a while back @orius123

**Comment by orius123** [comment]
Is there any serialization stuff in the logs?

**Comment by meirwah** [comment]
Your'e right.. it's anoter issue, it's because the SSH session fails in the middle of the flow

**Comment by meirwah** [comment]
It's a content issue...

**Comment by meirwah** [comment]
So seems like content issue. look at #116 at content issues..
