### ISSUE TITLE
test unstable

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#283]
https://travis-ci.org/CloudSlang/cloud-slang/jobs/60358482

[INFO] Test case passed: test1. Finished running: testFlowPath with result: SUCCESS
Tests run: 24, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.111 sec - in io.cloudslang.lang.tools.build.tester.SlangTestRunnerTest
Running io.cloudslang.lang.tools.build.tester.parser.TestCasesYamlParserTest
[INFO] No tests cases were found in: empty_file.inputs.yaml
[ERROR] Error loading file: wrongPath
java.io.FileNotFoundException: File 'wrongPath' does not exist
	at org.apache.commons.io.FileUtils.openInputStream(FileUtils.java:256)
	at org.apache.commons.io.FileUtils.readFileToString(FileUtils.java:1643)

**Comment by oritstone** [comment]
Not relevant
