### ISSUE TITLE
Remove the input1=input1 default expression behavior

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#286]

**Comment by oritstone** [comment]
Currently if the author did not specify a default value to an input, we assign to it by default an expression that is equal to the input name

**Comment by meirwah** [comment]
WHY??? we talked this over some many times and decided to go with the other way around?
it will cause many resgrassions now..

**Comment by orius123** [comment]
Behaviour will be the same but instead of treating it as an expression we just assign from key with the same name. Which is actually the same. Right @oritstone ?

**Comment by oritstone** [comment]
The behavior should stay exactly the same. The binding is done according to the input name if there is no default value.
It only means that we won't populate the expression if the author didn't specify it directly.
