### ISSUE TITLE
flow outputs fail when one of the flow steps fail

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#291]
lets say we have a flow with 2 steps , 1 and 2.
step 2 has output is "out2".
and flow has flow output called "flowout" (taken from param "out2")

flow fails at step 1, it will try to bind "flowout", and will fail (since it does not have "out2")...
maybe we need to change output behavior , to catch exception, and give default values  in case flow failed (or in any case??)

WDYT?

**Comment by Bonczidai** [comment]
I think the `get(var, default)` function solves this issue
