### ISSUE TITLE
System prop default value is problematic 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#302]
can search the whole computer since it searches from the dir you triggered cslang, should be ONLY current dir , @orius123  add to this

**Comment by oritstone** [comment]
@meirwah can it wait for 0.9?

**Comment by meirwah** [comment]
according to @orius123 this might be the reason for the performance issues at ubuntu .. if this is the case , then NO, this is an urgent bug must be solved for this version...

**Comment by orius123** [comment]
changed it to search only first level dir
