### ISSUE TITLE
Slang Events missing step deatils info

### ISSUE THREAD

**Issue by shajyhia** [CloudSlang/cloud-slang#306]
more information is needed for each task such as
step id
flow name 
flow uuid -> flow full name
step type (operation/subflow/branch)
running user Id

transition name

**Comment by orius123** [comment]
@shajyhia

**STEP_ID** has no meaning in CloudSlang terms.

@varelasavela is working on adding map of headers to score event for the platform to fill.
it should solve:
 - **FLOW_NAME**
 - **FLOW_ID**
 - **RUNNING_USER**

**STEP_TYPE** is already available in the latest slang build

For **TRANSITION_NAME** I will open a different issue. (will not happen in this sprint)
