### ISSUE TITLE
Cslang with content not compatible with last releases 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#307]
In previous releases you need to run a flow like this:
run --f ../../content/io/cloudslang/base/print/print_text.sl --i text=first_flow

but now:
run --f ../content/io/cloudslang/base/print/print_text.sl --i text=first_flow

Since versions are diff, I do not know what to write in the README anymore...

**Comment by orius123** [comment]
we agreed that it is better now and we will notify about it in 0.8 release notes
@meirwah if you agree please close

**Comment by meirwah** [comment]
but we need another issue to remember to change the README...

**Comment by oritstone** [comment]
Opened issue on site cloudslang/cloudslang.github.io#122
