### ISSUE TITLE
score-lang-api name is wrong 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#32]
it should be score-lang-all  .. or something else since it is not API it is package...

**Comment by oritstone** [comment]
I don't think the score-lang-all is a good name, since we will probably have a slang-all package that brings also score-all
Besides, it is a sort of API - the external API of Slang that allows for compilation, running flows (including creating the stuff we need on the contexts) and subscribing on events

**Comment by meirwah** [comment]
How is it API ??? that does not make sense...
API should be a small package to include only API , not the whole thing..

**Comment by oritstone** [comment]
What do you think about score-lang?
We have:
score-lang-compiler
score-lang-runtime
score-lang-entities
...
And score-lang is dependent on all 3 above, wraps them all.

I want to keep score-lang-all for a possible future packaging of score with score-lang

**Comment by oritstone** [comment]
Please let me know what you think, so I can change it.
Is score-lang a good name for the module?
Do you have other suggestions?

**Comment by meirwah** [comment]
:+1: on score-lang

**Comment by avimora** [comment]
Note that the parent is called `score-language`...
It IS a small package including only API, so `api` is fine IMHO

**Comment by oritstone** [comment]
It's true about the parent, but we don't have any artifact called score-language
Regarding the API name, it's true that it contains the Slang API, but it contains also the implementation, so it packs also the Slang compiler & Slang Runtime...

**Comment by okitac** [comment]
Given that everything refers to slang, it'd be helpful if the package made it clearer that you were building slang, not something separate that's a language for score.

**Comment by meirwah** [comment]
so @okitac should we just call the package **slang** ?
BTW Slang = score language...

**Comment by okitac** [comment]
It'd be clearer (or 'score-slang' ?).
While I do know that Slang == score language, it's not implicitly obvious if you don't know that (and/or how) score and slang are related.  I'll avoid the temptation of suggesting 'SLang', since it's not any clearer, and is far more annoying to type ;D

**Comment by meirwah** [comment]
:+1:

**Comment by oritstone** [comment]
I think we should wait with the rename of he module until we have a new name for the product...

**Comment by meshipeer** [comment]
that's ok
