### ISSUE TITLE
Tasks getting their inputs from flow inputs if not specified otherwise.

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#325]
I came across an idea while writing tests for the cloud-slang-content repository. I ended up having a set of inputs in a flow that where exactly the same (name) as the inputs of each of its tasks.

So I figured we could implement tasks first looking for the flow inputs. If a task's input would coincide with one of the flow's inputs (and no other value was specified for that input) then the task would get the value from the flow inputs without having to rewrite the inputs.

Example:
flow:
    name: a_flow
    inputs: 
        - input_1
        - input_2
    workflow:
      - task:
          do:
            namespace.operation:
               - input_1: "different than flow input"

In case the task contains an input named "input_2" it will take the value from the flow input. The way we have it not we have to also specify "input_2" in the task as well.
I figured this way, we can shorten a lot of flows that contain redundant input specification.
A good approach would be if both options would be available since in some cases it might be ambiguous.

Any comments are appreciated :)

**Comment by tudorlesan** [comment]
Actually, to avoid some ambiguities it could be that this feature will only be available if all the inputs of a task are found within the flow inputs. that way we can just say:

do:
namespace.operation(without ":" and the list of inputs)

Then we know that all the inputs for that operation are found in the flow inputs.

**Comment by oritstone** [comment]
I think that it is better that tasks state specifically which parameters they pass to the operation or flow.
We have another issue, however, issue (https://github.com/CloudSlang/cloud-slang/issues/288) that deals with simplifying the way we pass inputs to tasks - in order not to have to pass additional attributes on those inputs such as overridable.
@meirwah, @orius123 WDYT?

**Comment by orius123** [comment]
agree with @oritstone

**Comment by oritstone** [comment]
@meirwah, WDYT?

**Comment by meirwah** [comment]
agree with @oritstone , since this was the paradigm we choose (declare of inputs, so you know what you get ), i do not see this is the time to break it..
