### ISSUE TITLE
consistent download versions of CLI

### ISSUE THREAD

**Issue by gfachler** [CloudSlang/cloud-slang#333]
Discussed with Eliya and agreed on following:
readmes should have 2 links. one to download latest stable release and one 2 download latest snapshot
latest stable release should be that same release on readme, website, NPM, Docker etc.
We should release new stable release by end of this week

**Comment by orius123** [comment]
is this ready for merge?

**Comment by SamMarkowitz** [comment]
Should be handled by #335 and CloudSlang/cloud-slang-content#204.
