### ISSUE TITLE
Missing data about the task type in CloudSlang events

### ISSUE THREAD

**Issue by shajyhia** [CloudSlang/cloud-slang#341]
missing data about task type - if it runs a flow or operation

**Comment by oritstone** [comment]
We do not distinguish in CloudSlang betwen flow and operation, and therefore do not plan to add this information to our events

**Comment by shajyhia** [comment]
you do not distinguish between them just at execution stage but you do that at compiling time because the author was aware about what he was writing and i think he expect to see that at log of the execution

**Comment by oritstone** [comment]
We decided to add this data to the event.
Currently in Cloudslang DSL we distinguish between flow & operation, so we decided we will reflect this distinction also in the events

**Comment by orius123** [comment]
:-1:
