### ISSUE TITLE
Passing date object as default value of the input

### ISSUE THREAD

**Issue by varelasavela** [CloudSlang/cloud-slang#342]
Passing date object to the input as default value doesn’t work

**Comment by Bonczidai** [comment]
couldn't reproduce: I created a Java Date objects, passed it as a flow input and propagated in an action

p.s. in Java actions we had issues with Jython Date objects which are not serializable, therefore we cannot use them as action outputs - documented in [python_script section](http://cloudslang-docs.readthedocs.org/en/v0.9/cloudslang_dsl_reference.html#python-script)
