### ISSUE TITLE
missing event INPUT_START_ACTION for start input binding

### ISSUE THREAD

**Issue by shajyhia** [CloudSlang/cloud-slang#349]
today we have only INPUT_END_ACTION event thrown from Clang and it is not enough for cases of an exception happen at binding level

**Comment by varelasavela** [comment]
when CSlang fails on the input evaluation, event INPUT_START_ACTION is missing

**Comment by oritstone** [comment]
@shajyhia ,@varelasavela, did you mean we fire only **EVENT_INPUT_END** and not **EVENT_INPUT_START**?
