### ISSUE TITLE
Step inputs getting they're value from flow inputs even if specified otherwise

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#353]
So I know Donca Zsolt opened an issue about this after the Hackaton but it was disapproved. I don't remember the reasons for that though. Currently I'm looking over the test_report_mysql_status.sl which fails for reasons that I bumped into previously. Step inputs getting they're value from flow inputs even if a specific value was used.

This test flow has inputs like:
  - host
  - port
  - username  etc.

The problem arises when having at least two operations/subflows that have inputs with the same name ("port" for example) which require different values. In this specific scenario pre_test_cleanup, start_mysql_container etc. (and other steps that use docker) require one value for the port, while the verify_postfix step requires another.

Now for me at least, it seems odd to be able to specify for a step input a value like:
 - port: 25 
which is completely ignored and the value got is the value of the flow input with the same name. There are workarounds to that, but personally, I think this thing can cause many confusions, especially that it's not signaled in any way.

**Comment by tudorlesan** [comment]
what are your thoughts on this @orius123 @oritstone @meirwah

**Comment by tudorlesan** [comment]
BTW, I'm working on PR 214 on cloud-slang-content repo

**Comment by meirwah** [comment]
@orius123 @oritstone  please note this has implication on the change you plan for Task inputs, since the way to solve this is by "overridable false" on the task.. what we can not do after the change...

**Comment by orius123** [comment]
You can use overridable false to work around it for now, but actually I think that what @oritstone are suggesting will make this use case more straight forward because arguments will always be bound from the value that the user passed.

**Comment by meirwah** [comment]
how is that?
let's say you have two tasks, that are bound to ops that have inputs with name "port", 
you will need 2 flow inputs, port1, port2 .
how do you pass the right one to each task? if you do not have overridable false in task level??

**Comment by orius123** [comment]
Because the binding args behavior will be same as overridable false.

**Comment by meirwah** [comment]
that will be a major change... to switch the default behavior now....

**Comment by orius123** [comment]
As I see it it's a major change anyways. We need to go over all of the task inputs anyways..

**Comment by oritstone** [comment]
I think that the behavior of task inputs should be different than flow or operations inputs.
Actually, in tasks it is not inputs but arguments that are passed to the operation or subflow.
I think that in tasks the arguments should not support any property, besides supplying a default value, which will be always used if specified.
@meirwah @orius123 WDYT?

**Comment by orius123** [comment]
:+1:

**Comment by oritstone** [comment]
Closing this issue. Will address it when fixing #288
