### ISSUE TITLE
Async Loop events names are wrong

### ISSUE THREAD

**Issue by shajyhia** [CloudSlang/cloud-slang#355]
Currently i am using EVENT_ASYNC_LOOP_EXPRESSION_END and EVENT_ASYNC_LOOP_OUTPUT_END to support Async Loop but these two event names does not represent the action it self (JOIN,SPLIT) and could be missing some data about the number and names  of the branches and so.

i will recommend using the following names "EVENT_SPLIT_BRANCHES" and "EVENT_JOIN_BRANCHES"

**Comment by orius123** [comment]
regarding missing information: what is missing?
regarding naming: in general I agree, but currently all of our events has this non descriptive convention. (task ends with event_output_end and not something like task_end event for instance) so maybe it's a larger context for this one.

**Comment by shajyhia** [comment]
the missing information are depends on how we decide to render async loop.

Currently i am using EVENT_ASYNC_LOOP_EXPRESSION_END and EVENT_ASYNC_LOOP_OUTPUT_END to support Async Loop

**Comment by oritstone** [comment]
The bug is about changing the names of the events
