### ISSUE TITLE
Flow/operation inputs not being evaluated if inputs are given from the CLI

### ISSUE THREAD

**Issue by tudorlesan** [CloudSlang/cloud-slang#371]
operation:
  name: op1
  inputs:
    - first: value

Ok, so personally, I would expect this to fail by not being able to find variable "value", but this somehow succeeds if the "first" input is given from CLI.

**Comment by tudorlesan** [comment]
@orius123 is this the behavior that we expect?

**Comment by orius123** [comment]
if you pass `first` from the CLI than it binds it and doesn't got to the default.
IMHO this is how it should work.

**Comment by oritstone** [comment]
I agree with @orius123 the behavior is that if an input value is given to the CLI in triggering, it is bound to the input.
This behavior is exactly as we designed.
Do you see a problem with it @tudorlesan

**Comment by tudorlesan** [comment]
@oritstone I would just expect this check do be done before bounding the value from the CLI. Since this actually is a mistake, it seems misleading to have everything work fine if a value is given from the CLI, and fail if the incorrect value from script is used.

I would expect a compiler error to be thrown before binding the input from the CLI.

**Comment by tudorlesan** [comment]
I understand what @orius123 said that if a value is given from the CLI, the evaluation doesn't get to be executed. But since we refer to compiling a source, personally I would think that any error checking is done before assigning values from CLI.

**Comment by orius123** [comment]
You suggest that variables passed by the CLI that doesn't match outputs will be dropped?
I can live with that.

**Comment by tudorlesan** [comment]
No, I'm just saying that using the term "compiling" made me think that all possible script errors (like assigning to a flow input, a variable that does not exist) will be checked before binding values that were passed in the CLI.

Maybe I'm the only one that got confused by this. I can close the issue and if anyone else stumbles upon this it can be reopened.
