### ISSUE TITLE
The Zip file that users should download is very big (50MB)

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#381]
This can be a turn off for users who want to play with Cloud-Slang, the basic package should be very light and users will add additional capabilities if required

**Comment by Bonczidai** [comment]
we have been doing efforts to reduce the size of the CLI (clean requirements.txt file), the actions are no more stored in the lib, on the other hand we sacrificed some space for UX (packing maven dependencies for most common actions)

other jars that occupy space are like jython (! 35 MB), db .. which are all needed for current CS direction
