### ISSUE TITLE
When running command that requires an argument without specify the value, the error message is not clear

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#383]
We must improve the error messages because on many cases it's not clear what's wrong
for example,
Run: run –f
The error message is:
You should specify a default option (otherwise known as option 'f') for this command

**Comment by oritstone** [comment]
Related to #243

**Comment by lucian-cm** [comment]
@Bonczidai, is this fixed now?

**Comment by Bonczidai** [comment]
`run -f` gives `Command failed java.lang.IllegalArgumentException: File: -f was not found` since it's equivalent with `run --f -f` - I'd say it's fixed - @oritstone WDYT?

**Comment by oritstone** [comment]
I agree. Seems fixed

**Comment by lucian-cm** [comment]
Moving to closed based on previous comments
