### ISSUE TITLE
When there is a syntax error in a flow\operation the error messages is not clear enough, not easy to understand what is the problem and how it can be solved

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#384]
When tried to run a Python script with several lines got an error message that something is wrong with the YAML code, I think the error message should be more specific and indicate where exactly is the problem (character is missing, wrong indentation, etc…) 
Showing an example of common use cases can be very helpful, currently it’s very difficult to understand how to fix a problem 

When changed the operation structure (added some spaces & new lines) got an error that expected “block end” and found “block start”, according to the error message the problem was on the first line but the first line wasn't changed

**Comment by oritstone** [comment]
@nirgur we made some improvements regarding error messages.
Can you take the new CLI version from our website: http://www.cloudslang.io/#/getstarted#top, and check if it is fixed?
If not, can you please give some Cloudslang flows\operations examples that do not work well enough?

**Comment by oritstone** [comment]
Some issues are already fixed and some have specific cases open issues for them
