### ISSUE TITLE
When using an operation\subflow in a flow there is no indication about the inputs & outputs

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#386]
We should find a way to indicate which inputs & outputs a sub flow\operation has without opening it in an editor,
Currently when creating a flow that uses several operations the user should go back and forth between all the operations to see which inputs he should set for each one
Also the outputs is very confusing because the operations return outputs but in the main flow there is no indication where those parameters are coming from, again, the user should open each operation and checks which outputs it returns

**Comment by meirwah** [comment]
What about looking in the documentation area in the operation/flow? you can look this at GitHub (without opening the editor)

**Comment by nirgur** [comment]
But what if those flows are not on Github? maybe I got it from other team mate

**Comment by meirwah** [comment]
ok.. so what you suggest? a CLI option to print inputs+outputs?

**Comment by oritstone** [comment]
We plan in our road map to support some IDE.
I guess that as part of our IDE plugin, we will give some auto-complete options, such as suggestions for the inputs\outputs etc. Am I correct @meirwah?
Is it enough @nirgur or do you have additional suggestions?

**Comment by nirgur** [comment]
I think it won't be enough, for the outputs we can add an assignment in the main flow
maybe something like FLOW_PARAMETER = OPERATION.OUTPUT
I'm not sure what is the best syntax for that but it can help to understand where this parameter is set

regarding the inputs, I don't have a simple solution, maybe something like a plugin for IDE can help to present the expected inputs but when using text editors I don't think where is a way to solve it

**Comment by oritstone** [comment]
@nirgur, regarding the IDE plugin, we plan to add a plugin to a text editor we decide to support, to allow easier authoring of cloudslang flows, including auto complete.

Regarding your suggestion of OPERATION.OUTPUT, why do you think it is important to know if this parameter comes from the operation or from a previous task in the same flow? I think this syntax makes it more cumbersome.
I didn't really understand what are you trying to solve by it...

**Comment by oritstone** [comment]
After talking with @nirgur we concluded that the current behavior is OK
