### ISSUE TITLE
Cannot use external Python libraries in a flow

### ISSUE THREAD

**Issue by nirgur** [CloudSlang/cloud-slang#395]
I added the library to the requirements.txt file
installed it with pip and verified it was installed & added to the cslang\python-lib folder
when trying to run the flow getting the following error:

Command failed java.lang.RuntimeException: Slang Error : Error executing python script: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named svn

**Comment by nirgur** [comment]
@orius123 can you please assist? maybe I missed something

**Comment by orius123** [comment]
works for me :confused: 
even w/o a restart (CloudSlang/tutorials#10)

**Comment by oritstone** [comment]
@nirgur did you check it with the latest CLI version https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-0.8.RC1?

**Comment by jrosadohp** [comment]
Latest version fixed this for me.

**Comment by nirgur** [comment]
We found out what is the problem, @orius123 opened another issue
you can close this one
