### ISSUE TITLE
Can't execute SSH command from ready-made content

### ISSUE THREAD

**Issue by jrosadohp** [CloudSlang/cloud-slang#402]
Hi guys,

I'm trying to run the [ssh_command.sl](https://github.com/CloudSlang/cloud-slang-content/blob/master/content/io/cloudslang/base/remote_command_execution/ssh/ssh_command.sl) operation from the ready-made content.

This is what I'm running:

`run --f cslang/content/io/cloudslang/base/remote_command_execution/ssh/ssh_command.sl --i host=<IP>,command=ls,username=root,password=<PW>`

Here's the response:

```
- returnResult = Welcome to Ubuntu 14.04.2 LTS (GNU/Li...
- standard_out = Welcome to Ubuntu 14.04.2 LTS (GNU/Li...
- standard_err = stdin: is not a tty

Flow : ssh_command finished with result : SUCCESS
Execution id: 101600001, duration: 0:00:05.477
```

I get the `- standard_err = stdin: is not a tty` and no response for the `ls` command.

Adding the `pty=true` just makes flow yield FAILURE.

I'm probably missing something.

**Comment by orius123** [comment]
What you are facing with getting the entire Welcome page in the stdout is something we got also.
that is why we use ssh_flow that first start aconnection and that execute the command.
Regarding pty, saw it also but didn't drilled down to it yet. will take a look.
10X

**Comment by jrosadohp** [comment]
Oh, Cool. It worked!
Thanks
