### ISSUE TITLE
builder tool: enforce test order, before - after support

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#411]
to reduce build time - e.g.

swarm use case: each flow executes `setup_cluster` to be sure that swarm containers are running (another flow can clear the host between swarm test executions)

if we could specify a set of tests to be executed one after another the setup process should be executed only once (in this case we would win at least 5 min)

.. or a solution similar to this - `before test suite` - `swarm tests` - `after test suite`

**Comment by lucian-cm** [comment]
@Bonczidai are we still impacted by this after changes only feature?

**Comment by Bonczidai** [comment]
I think we can close this issue
