### ISSUE TITLE
Add to cli a "--debug" flag, to print each task Outputs  [3]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#415]
That way it will be easier to debug issues with flows...
should be added to the run cmd.

With different color to the outputs...

@orius123 @oritstone @Bonczidai @tudorlesan @SamMarkowitz @lirantal WDYT?

**Comment by orius123** [comment]
We should print also the results IMHO.
And of course exception full trace.

**Comment by meirwah** [comment]
agree @orius123

**Comment by tudorlesan** [comment]
Sounds great to me actually. This offers greater readability than the execution.log. But IMO the limit on which the output value is truncated and "..." is added, should be heightened a little bit. For me at least it seems that the output value truncates exactly before useful information is being printed.

**Comment by lirantal** [comment]
I like the idea Meir, definitely useful.

**Comment by meirwah** [comment]
Also @nwright-nz mentioned it...

**Comment by benc-uk** [comment]
Great idea! :exclamation: 
This will save having to add lots of `print` tasks when developing/debugging content
