### ISSUE TITLE
Introduce get('key', 'default') function for outputs [1]

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#420]
Many times when binding outputs the user need to check if a certain key is available in the context and if not bind a default value.
The way it is usually done is by `key' if 'key' in locals() else 'default'`.
I suggest we put a function that does this exact logic in the context when binding outputs,
than the user will be able to simplify his outputs to `get('key', 'default')`

**Comment by meirwah** [comment]
:+1:

**Comment by oritstone** [comment]
@orius123 do you mean using the python get method in our content?

**Comment by orius123** [comment]
Nope. Wrapping `locals().get(..)` with our `get(..)` method.

**Comment by oritstone** [comment]
So we will need to know when to parse the expression before eval and when not to...

**Comment by orius123** [comment]
Y? It is just a normal expression?
