### ISSUE TITLE
Improve looks of YAML parser errors (YAMLException)

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#43]

**Comment by meirwah** [comment]
Is this really needed? can i close this? @oritstone @orius123 ?

**Comment by oritstone** [comment]
I think it would be very usable to improve the parser error messages...
Nevertheless, I think it is not in such a high priority since you can usually understand something from it. It mainly not elegant enough...

**Comment by orius123** [comment]
:+1:

**Comment by Bonczidai** [comment]
there has been several improvements on the error messages - this issue is no more relevant
