### ISSUE TITLE
Running flow with inputs file in default location does not seem to work 

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#436]
according to this:
http://cloudslang-docs.readthedocs.org/en/v0.8/cloudslang_cli/#run-with-inputs

Input files can be loaded automatically if placed in a folder named inputs in the directory from which the CLI is run

Does not work for me (version 0.8)

**Comment by orius123** [comment]
Works for me when file under the directory I run from and has the word `inputs` somewhere in the file name.

**Comment by meirwah** [comment]
:+1:

**Comment by SamMarkowitz** [comment]
Still seems a bit unclear in the docs. Should I add something that says the file name must include `inputs` in it?

**Comment by meirwah** [comment]
yes @SamMarkowitz

**Comment by oritstone** [comment]
Opened https://github.com/CloudSlang/docs/issues/7
Closing this one
