### ISSUE TITLE
Loading custom classes from yaml (.sl) files

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#442]
In CloudSlang we use an `org.yaml.snakeyaml.Yaml` bean to load Yaml files. Now it constructed in the default way:

```Java
Yaml yaml = new Yaml();
```
according to https://code.google.com/p/snakeyaml/wiki/Documentation, in this form it allows to load custom objects from Yaml file - e.g. `"--- !org.yaml.snakeyaml.constructor.Person\nfirstName: Andrey\nage: 99"` this will be interpreted as a Person object

not now, but in the future this may cause security issues -- if we want to limit objects to standard Java objects like List or Long we need to use:

```Java
Yaml yaml = new Yaml(new SafeConstructor());
```

Q is whether we want to allow the loading of custom objects in our .sl files?

**Comment by orius123** [comment]
What is the security issue you are referring to?

**Comment by oritstone** [comment]
@meirwah do you think it is an issue we want to address?

**Comment by meirwah** [comment]
seems like it, not sure it's urgent...

**Comment by orius123** [comment]
Still didn't get the issue here..
Can you please explain what is it. please?.. :pray:

**Comment by Bonczidai** [comment]
I don't have a concrete example here.. it's more of a question (but we don't have that tag anymore)

thing is SnakeYaml doesn't recommend loading yaml docs from untrusted sources probably because of this issue.. once you can load your custom class, you can execute your code (.. if CloudSlang will be used as a webapp / web service)

**Comment by orius123** [comment]
You can load your class and execute malicious code in jython all over the place. People should know what are they running.

**Comment by Bonczidai** [comment]
issue not relevant
