### ISSUE TITLE
Latest release points to version without CLI-with-content [1]

### ISSUE THREAD

**Issue by meirwah** [CloudSlang/cloud-slang#452]
Look at version :
https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-0.8.0.1

![image](https://cloud.githubusercontent.com/assets/6059211/10068733/7910de1c-62af-11e5-9a1b-38188a20cba3.png)

Either we create a new release (WITH CONTENT , TAR+ ZIP) , or we move the link to 0.8.0 version

**Comment by oritstone** [comment]
Do we want the latest release to be 0.8.0.1 or 0.8.2?

**Comment by meirwah** [comment]
I think 0.8.0.1

**Comment by Bonczidai** [comment]
released manually: https://github.com/CloudSlang/cloud-slang/releases/tag/cloudslang-0.8.5

@oritstone do you think we can close this issue? (and open an another one for automation)
