### ISSUE TITLE
IDE Plugin - compilation errors [8]

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#456]
Support supplying compilation errors while writing CloudSlang content in an IDE

**Comment by lucian-cm** [comment]
@oritstone I think this can be closed, since there are enhancements for CloudSlang IDEA plugin and for the remaining outstanding items on compilation in cloud slang for the integration in IDEA plugin (Spring removal).
WDYT?

**Comment by lucian-cm** [comment]
@Bonczidai @gituser173 what do you think?

**Comment by Bonczidai** [comment]
I think we can close this issue once we open source the IntelliJ IDEA plugin - then, we can track items there

**Comment by oritstone** [comment]
@Bonczidai I agree

**Comment by tethryus** [comment]
The plugin had been added to the cloudslang repository.  Do you think that this issue can be closed?

**Comment by Bonczidai** [comment]
I think it can be closed sinced the IntelliJ plugin supports both warnings and errors
