### ISSUE TITLE
Issue with imports and dependencies

### ISSUE THREAD

**Issue by rqc** [CloudSlang/cloud-slang#457]
Hello,

I am using the docker image to create a container that runs some of your sample cs content. I noticed that in the docker container there is a pre-installed content under `/usr/cslang/cslang/content/` but if I follow the instructions here: http://www.cloudslang.io/#/getstarted#top I would need to backtrack on folder up like this: `run --f ../content/io/cloudslang/base/print/print_text.sl --i text=Hi`. So I think the instructions need to be changed or the example in the docs.

I was able to run the simple hello world example that way. 

I continued to run the container with a mapping of the updated cs content in the github.com. I want to do this to test some of the docker swarm flows that you have which are not part of the latest image. 

Howeve, when I try this script it fails:

```
➜  cloud-slang-content git:(master) docker run -it --rm -v $PWD/content:/usr/cslang/cslang/content --name cstest cloudslang/cloudslang
Database name is: H2 databaseMajorVersion is: 1
_________ .__                   .____________.__
\_   ___ \|  |   ____  __ __  __| _/   _____/|  | _____    ____    ____
/    \  \/|  |  /  _ \|  |  \/ __ |\_____  \ |  | \__  \  /    \  / ___\
\     \___|  |_(  <_> )  |  / /_/ |/        \|  |__/ __ \|   |  \/ /_/  >
 \______  /____/\____/|____/\____ /_______  /|____(____  /___|  /\___  /
        \/                       \/       \/           \/     \//_____/
0.7.14
Welcome to CloudSlang. For assistance type help.
cslang>run --f ../../content/io/cloudslang/docker/swarm/examples/print_cluster_info.sl
Command failed java.lang.RuntimeException: java.lang.RuntimeException: Error transforming source: demo_containers.sl to a Slang model. Unresolved alias: print_cluster_info
```

I read the documentation about setting the `--cp` and it is really not that clear how you should use it. Further guidance would be appreciate it. Thanks!

**Comment by meirwah** [comment]
Hi @rqc , I see that you use old CS version (0.7.14), please use the latest stable version (0.8), I think it will solve the issue you encounter...
You can also use latest Docker image for CloudSlang...

**Comment by Bonczidai** [comment]
@rqc do you still encounter the issue using latest docker image? (CloudSlang 0.8.0)

you should be able to run the flow with:

```
run --f ../content/io/cloudslang/docker/swarm/examples/print_cluster_info.sl --i <<input_list>>
```

**Comment by rqc** [comment]
@Bonczidai It did fix the issue. I pulled the `latest` and it is now `0.8.0`. I ran the command and it didn't complain about the imports.

Now I am having a different issue, but I will close this as solved and open a new issue. 

Thanks!
