### ISSUE TITLE
Question about running flow, shell or python scripts on remote host

### ISSUE THREAD

**Issue by rqc** [CloudSlang/cloud-slang#460]
Hello,

I have a use case where I would like to run a *series* of statements on a remote host in the form of a *script* or cloudslang *flow*. From the examples in the cloudslang-content repo, I have been able to run a simple command on a remote host. However, it is not clear, while using the cloudslang cli / engine, how I can run multiple commands without having a very long flow that just calles `ssh_command` one after another. What I would like is to have a python or bash script that I maintain, transfer it to the remote host, and then run it there. Does cloudslang provide any tooling to perform `scp` to a remote host? That would allow me to transfer the script and then just perform a simple `ssh_command` operation on that remote server. 

Thanks in advance!

**Comment by meirwah** [comment]
Hi @rqc , we are working on this, you can see the PR here : https://github.com/CloudSlang/cloud-slang-content/pull/50
Hopefully it will end soon...

**Comment by rqc** [comment]
OK. I will keep an eye on it. I was thinking that maybe this would be a similar Java API like the one you use for the ssh commands. However, using `scp` under the hood will do, but it would be great to have a working example from you guys first. Thanks!

**Comment by meirwah** [comment]
under the hood it will use Java API (https://github.com/CloudSlang/score-actions/tree/master/score-rft) 
that is already impl... we will try to provide examples for it once we merge this PR...

**Comment by Bonczidai** [comment]
Hi @rqc -- please note that *rft* operation is now available on master: `content/io/cloudslang/base/remote_command_execution/remote_file_transfer/remote_secure_copy.sl`

also the test flows may be used as usage examples:
```
test/io/cloudslang/base/remote_command_execution/remote_file_transfer/test_remote_secure_copy_local_to_remote.sl
test/io/cloudslang/base/remote_command_execution/remote_file_transfer/test_remote_secure_copy_remote_to_remote.sl
```

**Comment by rqc** [comment]
@Bonczidai Thank you so much. I will try to take a look at it this week. Awesome work guys!
