### ISSUE TITLE
errors from shell are misleading 

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/cloud-slang#470]
when running the run command like:
cslang>run write_to_file.sl
user get the error:
java.lang.IllegalArgumentException: Failed to convert 'write_to_file.sl' to type Boolean for option ',q,quiet
Cannot convert write_to_file.sl to type Boolean.

expected result: it should give the error that a flag is missing or not do nothing without any error...

**Comment by Bonczidai** [comment]
now `run file.sl` is translated to `run --f file.sl` (bugfix) so this issue is no longer applicable

**Comment by Bonczidai** [comment]
need to check whether it was fixed with recent encoding fixes
