### ISSUE TITLE
Help Run is missing examples

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/cloud-slang#471]
when running the command help run to try and understand how to use the inputs flag, it doesn't show examples

i'm sure that it could be added somehow also in other commands

**Comment by gituser173** [comment]
I think this one was already done. @mihaitusa can you also confirm this and see if you like how it is currently implemented?

**Comment by mihaitusa** [comment]
@gituser173  The examples are shown in help run command on CLI. @roieyal can you confirm with latest release 0.9.50 ?
