### ISSUE TITLE
user can't use the path to the flow using backslash

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/cloud-slang#472]
when running:
cslang>run --f C:\Roi\Tasks\cloudSlang\cslang-cli\cslang\cloud-slang-content-master\content\io\cloudslang\base\files\write_to_file.sl
user gets:
Command failed java.lang.IllegalArgumentException: File: write_to_file.sl was not found

workaround:user can switch all the slash into backslash

**Comment by oritstone** [comment]
Duplicate of #212
