### ISSUE TITLE
the logs folder is not located in the right place [1]

### ISSUE THREAD

**Issue by roieyal** [CloudSlang/cloud-slang#473]
logs folder should be somewhere in the cslang root folder maybe next to the bin folder

now it created the logs folder under content...

**Comment by maayan-avraham** [comment]
now it's creating the logs folder under the folder from which the cli was opened.
need to change the logs folder location to be under "cslang " folder

**Comment by Bonczidai** [comment]
applies also for `.history` file

**Comment by Bonczidai** [comment]
btw don't we want this for the builder too? WDYT? @oritstone

**Comment by oritstone** [comment]
@Bonczidai I think we do. Please open an issue
