### ISSUE TITLE
Enforce the relation between the namespace and location of the .sl file

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#474]

**Comment by orius123** [comment]
On the cli? Why?

**Comment by Bonczidai** [comment]
found by users during TTV testing -- we need to discuss if we want it or not

**Comment by oritstone** [comment]
On the compiler
We need to discuss if we want to enforce it by failing compilation

**Comment by oritstone** [comment]
@mbettan, @benc-uk, @lirantal, @CloudSlang/slang-functional-reviewers, @orius123 @meirwah 

We are currently not enforcing by the CloudSlang compiler that a flow or operation namespace will be derived from it's folder path on the file system. 
Meaning that if you write a flow or operation and give it a namespace which is not related to it's path, it will pass compilation. We only document it as a best practice, but **we do enforce it on contributions to our repository**.
We need to decide if it is better to enforce it already on the compiler, meaning that you cannot write a flow (even if it is on your local repo) without aligning the namespace to the path. 
WDYT?

**Comment by orius123** [comment]
When you say compiler do you mean CLI?
Brcause compiler doesn't get file as input it gets a string. Right?

**Comment by oritstone** [comment]
Yes, you are write. Sorry for the inaccuracy :)

**Comment by Bonczidai** [comment]
I would not enforce it in CLI, rather fire warnings and handle it in CloudSlang IDE (Atom): signaling it and adding the ~ `move to correct folder structure` capability

**Comment by avigail-oron** [comment]
I think it should be enforced. It's not unreasonable to require that from the author and it saves a lot of pain later on

**Comment by meirwah** [comment]
same as @Bonczidai on this..

**Comment by orius123** [comment]
I think it's the build utility responsibillity, does java warn when files aren't under `src` folder??

**Comment by benc-uk** [comment]
Not really, the Java compiler doesn't care what folder structure your classes are in.
So I can declare a class as being in a Java package, e.g: `package: com.ben.test;` but put the `.java` file into any folder or sub-folder structure I want to, and it will compile fine

The only convention the Java compiler enforces is the file name matches the class name e.g. `dog.java` can not contain a class called "cat"

**Comment by gituser173** [comment]
I agree with @Bonczidai I think this should not be enforced but maybe we could have a warning.
WDYT? @CloudSlang/slang-functional-reviewers

**Comment by orius123** [comment]
:+1:

**Comment by avigail-oron** [comment]
making it easy for the author to do it in a less restrictive manner is nice, but the author will pay later on  when moving to the studio.
if it were me - i would prefer to avoid this in advance rather then pay later on.
i believe a warning will not be sufficient.

**Comment by orius123** [comment]
I agree that studio is important but cloudslang is (supposed to be) an autonomous language, so I don't think we need to mix their concerns, build tool is more related to this issue. although cli does cloudslang doesn't even require an actual file.
