### ISSUE TITLE
Enforce flow name and file name to be identical

### ISSUE THREAD

**Issue by maayan-avraham** [CloudSlang/cloud-slang#489]
*fail compilation* if flow name and file name are different.
(doing it through the CLI)

**Comment by orius123** [comment]
Didn't we had this one already? (and decided not to..)

**Comment by oritstone** [comment]
We have another issue (#474) about enforcing the relation between the namespace and location of the .sl file 
And even there we did not reach a conclusion yet...

**Comment by gituser173** [comment]
I think this should be enforced, similar to what Java does with class names.
WDYT? @CloudSlang/slang-functional-reviewers

**Comment by avigail-oron** [comment]
agree

**Comment by orius123** [comment]
:+1:
