### ISSUE TITLE
Remove Apache commons-collections4-4.0.jar when embedding in OO

### ISSUE THREAD

**Issue by lucian-cm** [CloudSlang/cloud-slang#501]
When the following dependency is used in OO

```
<dependency>
            <groupId>${cloudslang.groupId}</groupId>
            <artifactId>cloudslang-all</artifactId>
            <version>${cloudslang.version}</version>
        </dependency>
```

as a third party dependency `commons-collection4` version `4.0` is brought, making duplicate classpath entries in Operations Orchestration Central for cloud slang version 0.8.0.1.

**Comment by gituser173** [comment]
https://www.us-cert.gov/ncas/current-activity/2015/11/13/Apache-Commons-Collections-Java-Library-Vulnerability

https://www.kb.cert.org/vuls/id/576313
"Apache Commons Collections version 3.2.2 and version 4.1 has been released. These new releases mitigate the vulnerability by disabling the insecure functionality."

@lucian-cm I will update to version 4.1 in master.
