### ISSUE TITLE
Operation labelled as flow

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang#531]
When running an operation directly from the CLI (without a calling flow) the text printed to the screen still says "Flow outputs:" and "Flow xxx finished with result :".

It's a little misleading.

**Comment by orius123** [comment]
we can make it "Run outputs:" is it better?

**Comment by SamMarkowitz** [comment]
Seems fine to me.

**Comment by oritstone** [comment]
:+1:

**Comment by SamMarkowitz** [comment]
If it's not such a bother (which it seems not to be), I suggest:

+ When running a flow:
  + "Flow outputs: ..."
  + "Flow: flow finished with result: ..."
+ When running an operation:
  + "Operation outputs: ..."
  + "Operation: operation finished with result: ..."

And while we're at it I think we can do away with the repetition of "flow" (or "operation") in  "Flow: flow finished with result: ...".

I suggest just printing "Flow finished with result: ..." or "Operation finished with result: ..."

And finally, with the risk of being too annoying, the "Flow outputs:" line prints even when there are no outputs. It might be better to not have that line print when there is no information being relayed.

**Comment by gituser173** [comment]
![capture](https://cloud.githubusercontent.com/assets/12094982/12193988/0b51ac96-b5f5-11e5-8599-d89948837a0b.PNG)
