### ISSUE TITLE
Inputs and Arguments binding data is sent in the events as map and not list

### ISSUE THREAD

**Issue by oritstone** [CloudSlang/cloud-slang#532]
Arguments and inputs are lists (have order)
The events fired contain this data as maps and not list, so the order is missing

**Comment by gituser173** [comment]
@oritstone 
The data in the sendEndBindingInputsEvent event is contained in a LinkedHashMap so the order is maintained. In the sendStartBindingInputsEvent event the inputs names are in a List so there is order here also.
The RunEnvironment object contains the input data as HashMap so there is no order here, you want this to be changed to LinkedHashMap so we have order also here?

**Comment by oritstone** [comment]
You are right. My bad... :)
I don't think there is a need to keep the order in the RunEnvironment object
