### ISSUE TITLE
Properties files with .sl extension

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#549]
rethink how to distinguish between SP and executable .sl files (now it's in CLI / builder naive implementation)

**Comment by Bonczidai** [comment]
the issue that we need to discuss: should SPs be really .sl files?

SP files have a certain structure, but it does not necessarily need to be CloudSlang file. `.sl` files were only executables (flows / ops) before. We need to distinguish clearly between executables / SP files (in the future, maybe inputs files).

[CloudSlang API](https://github.com/CloudSlang/cloud-slang/blob/master/cloudslang-all/src/main/java/io/cloudslang/lang/api/Slang.java) has methods like:
```Java
CompilationArtifact compile(SlangSource source, Set<SlangSource> dependencies);
Long run(CompilationArtifact compilationArtifact, Map<String, ? extends Serializable> runInputs, Set<SystemProperty> systemProperties);
Long compileAndRun(SlangSource source, Set<SlangSource> dependencies, Map<String, ? extends Serializable> runInputs, Set<SystemProperty> systemProperties);
Set<SystemProperty> loadSystemProperties(SlangSource source);
```

the api's methods accept a source and do something with it, at this level it is expected from the caller to know the type (now we distinguish in upper layers like CLI based on top level tag (e.g. properties / flow / operation - not so cool)

so I see two options here:
- we really want SP files to be `.sl` -- lot of redesign, common class for Executable and SPs, SP files will be **compileable** (no loadSP() methods)
- they will have another extension (`.properties` / `.prop`/ `.sp` maybe `.properties.sl`) - they will be loadable, we know in upper layers clearly what to pass to compile and what to pass to loadSP methods

I don't say that the `.sl` approach is bad, just too much effort comparing to the benefits -- logically SP files have structure which is verified, but I think they should remain loadable only (not compilable)

**Comment by Bonczidai** [comment]
@oritstone @meshipeer let's hear WDYT

**Comment by orius123** [comment]
what are the benefits? namespace?
can't it be just YAML?

**Comment by oritstone** [comment]
I think that it is better that system properties files will have a specific, different extension (i.e. `.sp`, `spl`)
This way we can distinguish between executable & system properties and still be able to have a pre-defined structure for system properties and use namespace

**Comment by Bonczidai** [comment]
I would also go with `.sp`

are there any objections?

**Comment by meshipeer** [comment]
i prefer the .prop.sl - i think its better to have one extension (also for IDE plugin and to help the user understand its for CloudSlang

**Comment by aeskin** [comment]
.prop.sl sounds reasonable

**Comment by Bonczidai** [comment]
`.prop.sl` it is then

**Comment by avigail-oron** [comment]
prop.sl makes sense
