### ISSUE TITLE
MetadataExtractor enhancement

### ISSUE THREAD

**Issue by gituser173** [CloudSlang/cloud-slang#558]
Extract the namespace from the .sl file and add it to the Metadata pojo that is returned by the MetadataExtractor interface.

**Comment by meshipeer** [comment]
what about the descriptions?

**Comment by Bonczidai** [comment]
**IMHO description section -> MetaData, namespace -> Language Data**

As I see the metadata is now extracted from two sources: `#!` comments (user defined MD, I can put anything here, not enforced to be semantically correct), CS code (`namespace` of the executable - compiled, validated)

**Y do we need this? we have the NS after precompile stage..**
