### ISSUE TITLE
System properties containing '-' are not returned by CompilationArtifact

### ISSUE THREAD

**Issue by aeskin** [CloudSlang/cloud-slang#560]
For example, this is a fragment of a flow (below). I would expect 2 system properties to be returned by CompilationArtifact, but 0 are returned. We can tell that hyphens are not allowed for Slang SPs, but for AFL ones we cannot enforce this limitation.
flow:
  inputs:
    - input_afl : ${ get_sp('afl-deployment-cp-slangsp-5-01') }
    - input_slang : ${ get_sp('slang-deployment-cp-slangsp-5-01-03') }

**Comment by Bonczidai** [comment]
currently accepted characters are the word characters (A-Za-z0-9 and underscore). We can add `-` to this set

**Comment by Bonczidai** [comment]
@oritstone @meshipeer @aeskin do you think we should allow other characters than alphanumeric, underscore and hyphen in system property names?

**Comment by aeskin** [comment]
Following are the valid characters for naming configuration items in AFL (from the OO Authoring Guide):
• Alphanumeric characters
• Spaces
• Curly, round and square brackets and full width brackets
• Underscore, full width underscore
• Hyphen, full width hyphen
• Dot, full width katakana dot, full stop, ideographic half width stop, half-width katakana middle dot, ideographic full stop, katakana middle dot, middle dot

**Comment by Bonczidai** [comment]
thanks @aeskin - I think we can go with the `A-Za-z0-9_-` set (I don' think we should add space, brackets etc. - dot is the separator in the FQN)
