### ISSUE TITLE
Document a list of all the special characters supported in input names

### ISSUE THREAD

**Issue by SamyQA** [CloudSlang/cloud-slang#561]

**Comment by gituser173** [comment]
Special characters are not supported in input names. Input names should be written in snake_case.
http://cloudslang-docs.readthedocs.org/en/v0.9/cloudslang_best_practices.html

**Comment by gituser173** [comment]
Input names have two constraints: 
1) python variable names constraint: https://en.wikibooks.org/wiki/Think_Python/Variables,_expressions_and_statements#Variable_names_and_keywords
2) java variable names constraint: see "Naming" section https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html

**Comment by SamMarkowitz** [comment]
@gituser173 when you say "Input names" do you mean to also include outputs and published variables (my guess is results are not included in the restriction). Please confirm and add anything that is missing.

Restricted:
- [ ] inputs
- [ ] outputs
- [ ] published
- [ ] results

**Comment by gituser173** [comment]
@SamMarkowitz all variable names are affected, not their values.
