### ISSUE TITLE
Need to know if the input names and values support different language characters

### ISSUE THREAD

**Issue by SamyQA** [CloudSlang/cloud-slang#562]
Need to know if when running on a Japanese, German or some other localized environment, the user is able to use the localized characters for input names and input values.
Example of values  噂閏云ボ厭ポ院ｱ, ÄÖÜßÁÀÂÉÊ€äöü°áàâéê¢

**Comment by gituser173** [comment]
Localized characters are not currently supported for input names.

**Comment by SamMarkowitz** [comment]
@gituser173 

I'm trying to follow this for the docs. What is the bottom line here? "Localized characters not supported for input names"? What constitutes localized characters? 

But values can be any UTF-8 characters, correct?

**Comment by gituser173** [comment]
Yes values can be any encoding you specify in the cslang.properties from the "configuration" folder

**Comment by Bonczidai** [comment]
:+1: 
@gituser173 please describe in details how the config file works and what are the supported properties - it is very important to document this feature

**Comment by gituser173** [comment]
The config file named "cslang.properties" should contain a "cslang.encoding" property and it's value will be the encoding that CloudSlang will use for input values/input files.
For example:
cslang.encoding=utf-8
