### ISSUE TITLE
Be able to extract language data from flows that may be incorrect but valid Yaml

### ISSUE THREAD

**Issue by maayannoy** [CloudSlang/cloud-slang#564]
When creating new flow the workflow is empty.
When trying to compile this flow in order to get the namespace, for example, we get an error that our workflow is empty.
Can we make such scenarios legal in compiler?

thank

**Comment by Bonczidai** [comment]
@oritstone @meshipeer do you see any reason not to allow empty workflow?

**Comment by meshipeer** [comment]
for pre-compile it make sense! - compilation should fail

**Comment by oritstone** [comment]
We currently have all of our validations during the pre-compile, and I think it is OK this way
Maybe we should add another API for extracting meta-data, that will not do any validations, but just try to extract all the meta-data it can from the cloudslang source
For sure these 2 APIs should share almost all of the code...

**Comment by Bonczidai** [comment]
I could live with @oritstone 's suggestion - however

- I don't think the namespace is metadata, it is part of the DSL
- if compilation fails, it means we have a corrupted file and we are extracting data from it - is it a valid use case to extract the namespace of a corrupted file?

**Comment by oritstone** [comment]
Sorry, the term meta-data was inaccurate. I meant extracting the executable's API: type, name, namespace, inputs, outputs, results
But it is a valid question if we want this API as part of our cloudslang repository...

**Comment by Bonczidai** [comment]
Problem is: be able to extract language data from flows that have correct syntax, but are not necessary valid from logical POV (e.g. no tasks, invalid navigation)

Details:
•	Stages: parse + model + compile to EP
•	Currently fails on the first problem
Solution:
•	Rewrite the modeling stage so that we will extract all the data that is possible and collect all the errors

**Comment by oritstone** [comment]
Clarification on the problem - flows may have incorrect syntax, but can be parsed as valid Yaml, and some of the data is valid. For example only the namespace attribute is valid

**Comment by Bonczidai** [comment]
adding @Ligia-Andreica
