### ISSUE TITLE
inspect adds extra quote characters to doc section

### ISSUE THREAD

**Issue by SamMarkowitz** [CloudSlang/cloud-slang#565]
When running an `inspect` on a file that has quote characters (single or double) the displayed documentation has extra quotes in it. 

For example, see \content\io\cloudslang\base\json\add_value.sl

```
####################################################
#!!
#! @description: Adds or replaces a value to the given JSON at the keys or indices represented by the json_path.
#!               If the last key in the path does not exist, the key is added as well.
#! @input json_input: JSON data input - Example: '{"k1": {"k2": ["v1", "v2"]}}'
#! @input json_path: path at which to add value represented as a list of keys and/or indices - Example: ["k1","k2",1]
#! @input value: value to associate with key - Example: "v3"
#! @output json_output: JSON with key:value added
#! @output return_result: parsing was successful or not
#! @output return_code: "0" if parsing was successful, "-1" otherwise
#! @output error_message: error message if there was an error when executing, empty otherwise
#! @result SUCCESS: parsing was successful (return_code == '0') and value was added
#! @result FAILURE: parsing was unsuccessful or the path does not exist
#!!#
####################################################
```

![image](https://cloud.githubusercontent.com/assets/9436355/13051364/880ca69e-d401-11e5-9bf1-86acad06ccaf.png)

**Comment by gituser173** [comment]
@SamMarkowitz WDYT?
![capture](https://cloud.githubusercontent.com/assets/12094982/13630199/c2d00234-e5e6-11e5-8937-80b65b8f0207.PNG)

**Comment by SamMarkowitz** [comment]
Looks good. 

Would be even easier to read if wrapped lines were indented, but I'm guessing that's not possible since where it wraps it user dependent.

Do you think it makes sense to remove sections that don't have any entries, like prerequisites in the above example?
