### ISSUE TITLE
Some builder validations do not indicate the file in which the problem occurs

### ISSUE THREAD

**Issue by SamyQA** [CloudSlang/cloud-slang#567]
I have more .sl files in my content which I try to validate using cloudslang-builder.
I am receiving some syntax error with specific line and column identification, but there is no indication about in which file it occurs.
![image](https://cloud.githubusercontent.com/assets/17079492/13178528/fd3b9d98-d727-11e5-84ff-7b33286b4823.png)

**Comment by gituser173** [comment]
Looks like it is not reproducible anymore:
![capture](https://cloud.githubusercontent.com/assets/12094982/13570076/bd3c0764-e474-11e5-8ecb-fc72201ceec6.PNG)

**Comment by SamyQA** [comment]
OK... I dind't verified it, but in your console looks good now.

**Comment by mihaitusa** [comment]
@SamyQA  @gituser173  Verified with the last builder. Every time the problematic file was prompted in the output. The bug is not reproducible. IMHO can be closed.
