### ISSUE TITLE
Remove `self` keyword - context visibility

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#568]
Consider case of a task-subflow (it also applies to operation-action, aggregate section etc.) in the publish section.

Behavior now:
- visible context: subflow context
- reference flow contex: with `self` keyword

Usage is rare and confusing, so we suggest to go with:

Behavior after the change:
- visible context: flow context + subflow outputs (takes priority)
- we will fire a warning when var name is identical in subflow outputs and flow context
  - checking the conflicts at compile time may be an option - but we need to take into account flow inputs and publish sections (all the possibilities that modify flow context - not sure it's a good idea)

@CloudSlang/slang-functional-reviewers please give feedback

**Comment by orius123** [comment]
I'm against overriding. even with a warning.

**Comment by Bonczidai** [comment]
note here: self gives flexibility, but it will also make things complicated in each place where we have these two contexts - e.g. in case of sensitive data, we will need two forms of the `get` function instead of one

**Comment by meshipeer** [comment]
since the self[] syntax must change to a method (for the transitive sensitive data)
and since for the requirement of dynamic navigation (based on outputs and inputs) we do need the inputs and they don't rare at all...
I like more the fact that you need to know what you use + i also agree that we need to have the same syntax in the publish and in the navigate
my suggestion:
get() - uses for the inputs
get_output() or output() will be used for the outputs
WDYT?

**Comment by oritstone** [comment]
I agree it's better to keep the distinction, and be able to state where we take the value from
I think, however that the more common use case is using the outputs of the subflow than the current flow inputs. So I think that the simpler syntax should be used for the outputs (`get()`) and find another syntax for the inputs

**Comment by Bonczidai** [comment]
:+1: agreed

I also think that outputs should be default context - access like `var_name`, `get('var_name')` etc.
we will use a function to reference the context before the subroutine - we will need to find a good name - `get_self` (?)

**Comment by Bonczidai** [comment]
result of discussions - we will change contexts visibility, that way we will not need special keywords for accessing them

summary:

| place / accessable context | context passed to the executable (user supplied, result of binding) | flow context | operation context (bound input values) | action outputs context | subflow / operation output context | task arguments           | already bound values  |   |   |   |   |   |   |   |
|----------------------------|---------------------------------------------------------------------|--------------|----------------------------------------|------------------------|------------------------------------|--------------------------|-----------------------|---|---|---|---|---|---|---|
| flow inputs                | Yes                                                                 |              |                                        |                        |                                    |                          | no - discussions here |   |   |   |   |   |   |   |
| flow outputs               |                                                                     | Yes          |                                        |                        |                                    |                          | no - discussions here |   |   |   |   |   |   |   |
| operation inputs           | Yes                                                                 |              |                                        |                        |                                    |                          | no - discussions here |   |   |   |   |   |   |   |
| operation outputs          |                                                                     |              | Yes (P1)                               | Yes (P0)               |                                    |                          | no - discussions here |   |   |   |   |   |   |   |
| operation results          |                                                                     |              | Yes (P1)                               | Yes (P0)               |                                    |                          |                       |   |   |   |   |   |   |   |
| task argument              |                                                                     | Yes          |                                        |                        |                                    |                          | no - discussions here |   |   |   |   |   |   |   |
| task publish values        |                                                                     |              |                                        |                        | Yes - compile time check           | Yes - compile time check | no - discussions here |   |   |   |   |   |   |   |
| task navigation section    |                                                                     |              |                                        |                        | Yes - compile time check           | Yes - compile time check | no - discussions here |   |   |   |   |   |   |   |
| task aggregate section     |                                                                     |              |                                        |                        | Yes - compile time check           | Yes - compile time check | no - discussions here |   |   |   |   |   |   |   |
| action inputs              |                                                                     |              | Yes                                    |                        |                                    |                          |                       |   |   |   |   |   |   |   |
|                            |                                                                     |              |                                        |                        |                                    |                          |                       |   |   |   |   |   |   |   |
|                            |                                                                     |              |                                        |                        |                                    |                          |                       |   |   |   |   |   |   |   |


notes:
- P0 context overrides P1 context

changes:
- task publish values / results can be bound from subflow outputs (higher priority) and task arguments
- compile time check: task arguments cannot have the same name as subflow outputs (so we will see clearly what we bind from)

**Comment by orius123** [comment]
First of all - :clap: @Bonczidai you are a markdown ninja!
Regarding the compile time limitation, don't we save only a ref to the subflow, and the user can actually swtich the real subflow when running (pass a different compiled artifact as the ref in the dependencies)? if so, we can't enforce it.

**Comment by Bonczidai** [comment]
you are right as always :muscle: - wouldn't be a good idea to enforce it
in this case subflow outputs will have priority over task arguments
