### ISSUE TITLE
slang events step type

### ISSUE THREAD

**Issue by orius123** [CloudSlang/cloud-slang#6]
Currently there is no decent way to know the slang event type (exec or task) is by the ExecutionPath inner enum.
I think we should give a better way.
@avimora WDYT?

**Comment by avimora** [comment]
Agree. It's actually on LanguageEventData. Adding @meirwah

**Comment by meshipeer** [comment]
agree too

**Comment by oritstone** [comment]
+1

**Comment by avimora** [comment]
How about having 2 fields on the event: `step type` and `step name`?

**Comment by oritstone** [comment]
Fixed by #300
