### ISSUE TITLE
CLI verbosity levels

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#611]
use this issue to brainstorm on CLI verbositiy level naming - now we have:

quiet - default - debug

**Comment by SamMarkowitz** [comment]
I've done some digging (again I think) and here's what I've found:

1. There doesn't seem to be any standard way of doing this.
2. Commonly done with numbers 0-x or low/medium/high type levels. (I personally don't like this style.)
3. Also commonly done on logs with some variation on fatal, error, warn, info, debug levels. (Doesn't work for our verbosity levels.)
4. Other terms used are: detailed, diagnostic, general, informational, minimal, normal, quiet, verbose.

Given the above, I kind of like what we have now.

**Comment by Bonczidai** [comment]
agree :+1: 

.. git also support `--quiet` flag
