### ISSUE TITLE
Add function for null check

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#614]
new funcitonality: func(expr1, expr2) <--> if expr1 != null then expr1 else expr2 

current get: expr1: globals().get(key)

**Comment by Bonczidai** [comment]
since `get(param1)` and `get(param1, param2)` forms are already taken by `get` functionality where `param1` is `globals().get()` we cannot use the same name (no overloading is possible) -- it's similar to the case of `get_sp` (we needed a different name)

so, we need a good name for this functionality: `func(expr1, expr2) <--> if expr1 != null then expr1 else expr2`

name? -- now we have `get` and `get_sp`
- get_expr(expr1, expr2)
- ...

p.s. there were questions about the condition - whether it should be `expr !=null` or `expr` (~ `bool(expr)`) - the second form is no good, since it looks for boolean values, everything that is not evaluated to False will be True (this is not the case here)

**Comment by avigail-oron** [comment]
@Bonczidai - can you please explain why is the get(x,y) akready taken? what do x and y stand for?

**Comment by Bonczidai** [comment]
get(x,y): x is a key in the context, y is the default value

function bodies:

```python
def get(key, default_value=None):
  value = globals().get(key)
  return default_value if value is None else value

def get_sp(key, default_value=None):
  property_value = __sys_prop__.get(key)
  return default_value if property_value is None else property_value
```

 how the `get_expr()` would look like:
```python
def get_expr(expr1, expr2=None):
  return expr2 if expr1 is None else expr1
```

**Comment by guyhanael** [comment]
I would go with eval(expr,expr)

**Comment by orius123** [comment]
I believe `expr1 or expr2` is supported by Python. Can't check right now.

**Comment by Bonczidai** [comment]
@guyhanael unfortunately `eval` is already taken in [Python](https://docs.python.org/2/library/functions.html#eval)

@orius123 good idea, it works in Python -- however there is slightly difference between `expr2 if expr1 is None else expr1` and `expr1 or expr2` -- the second form uses Python [truth values testing](https://docs.python.org/2.4/lib/truth.html) which means values like `[]` are considered false --- for us they are valid values

@SamMarkowitz can you jump inhere? you are good with naming

**Comment by orius123** [comment]
You can check in those cases for none. `(something that returns an empty array) is not None or expr2`

**Comment by orius123** [comment]
Anyways what about `check_empty(value, default)` or just `empty...`

**Comment by SamMarkowitz** [comment]
Did a little research as to how others do this. Looks like various SQL functions are quite similar:

- [NVL] (https://docs.oracle.com/cd/B19306_01/server.102/b14200/functions105.htm): don't like this name, not even sure what it means - something with "null" and "value" i guess
- [COALESCE](https://docs.oracle.com/cd/B28359_01/server.111/b28286/functions023.htm): also strange name and original function has slightly different functionality than what you're proposing
- [ISNULL](https://msdn.microsoft.com/en-us/library/ms184325.aspx): this one isn't bad, although the "is" makes it seem like it would return a boolean
- [REPLACENULL](https://msdn.microsoft.com/en-us/library/hh479601.aspx): also not bad, although the "replace" doesn't make 100% sense if `expr1` isn't null

I think `check_null` might work best. I'm still not totally satisfied yet. Still thinking.

**Comment by orius123** [comment]
I prefer `check_empty` (yes, I know I offered it.. :smile: ) because `null` is Java Term and in python is `None`.

**Comment by Bonczidai** [comment]
`check_empty` it is then
