### ISSUE TITLE
clang-builder (9.16) is failing flows that have task inputs with value null

### ISSUE THREAD

**Issue by SamyQA** [CloudSlang/cloud-slang#616]
This CP contains .sl files with some taks that have inputs defined with null values

[project1-cp-1.0.0 (1).zip](https://github.com/CloudSlang/cloud-slang/files/186028/project1-cp-1.0.0.1.zip)

When validating using the cslang-builder, it fails because of the inputs that have null values

**Comment by Bonczidai** [comment]
thanks @SamyQA -- this thread will be continued in #613
