### ISSUE TITLE
Add compile functionality to cli

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cloud-slang#636]
Imagine:
1. building a large flow with sub-flows and operations.

**Expected result:**
a. that you want to compile everything to avoid compile related errors at run-time.
b. that you want all the compile errors to be displayed not errors to appear one by one

**Actual result:** At run-time (using the run command) compile errors are triggered which are hard to differentiate among other errors and appear one by one.

Example:
`cslang>run --f /tutorials/base/print.sl --i text=Hi
Command failed java.lang.RuntimeException: java.lang.RuntimeException: For operation 'print' syntax is illegal.
Could not transform Input : {text=null} Since it has a null value.

Make sure a value is specified or that indentation is properly done.`

**Comment by gituser173** [comment]
usage: compile --f FILE_PATH --cp DEPENDENCIES_FOLDER_PATH
