### ISSUE TITLE
Cannot Clone VM to different datastore

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang#640]
Steps to reproduce:
Expected result: The machine 'alexCStestVM', which resides on "dataStore":"CMSOO-D-EVA1" is cloned to clone_data_store: "CMSOO-F-EVA1", which is associated with the host "blade01-08-v163.rose.hp.com": of both the source and the clone machines

Actual result: 
The operation fails with

"Operation outputs:
- error_message = java.lang.RuntimeException: The specified Datastore was not
und.
- return_result = java.lang.RuntimeException: The specified Datastore was not
und.
- return_code = -1"

**Comment by dumagalex** [comment]
Clone VM runs successfully when cloning to a different host, associated to the same datastore

**Comment by mihaitusa** [comment]
Already fixed... I will supply the jar that contains the fix.

**Comment by mihaitusa** [comment]
fixed in https://github.com/CloudSlang/score-actions/pull/104

**Comment by dumagalex** [comment]
Passes confirmation testing against the supplied jar file, on both vSphere 4.1& 6.0: could clone VM to different datastore associated with different host

**Comment by mihaitusa** [comment]
@dumagalex Thanks for your help on QA validation effort. I will close this bug.
