### ISSUE TITLE
Clone VM doesn't work when no folder_name is given

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang#641]
Expected result: A clone is created, since the inputs above are the only required ones

Acual result: The operation fails with an "operation not supported on the object" error

**Comment by mihaitusa** [comment]
Fixed in #104

**Comment by mihaitusa** [comment]
@dumagalex Please let us know the results of validation

**Comment by dumagalex** [comment]
Clone VM works successfully on a subsequent build even when folder_name (not required) is not initialized. On both vmware 4.1.0 and 6

**Comment by mihaitusa** [comment]
@dumagalex Thanks for your help on QA validation effort. I will close this bug.
