### ISSUE TITLE
io.cloudslang.lang.compiler.SlangSource#fromBytes fails when the fileName includes .sl extension

### ISSUE THREAD

**Issue by aeskin** [CloudSlang/cloud-slang#648]
This doesn't make any sense. If a fileName is expected in the method signature, it should contain the extension. If an operation name is expected, why should I know it before compiling the source?

**Comment by Bonczidai** [comment]
I suggest the following methods to create a `SlangSource(content, name)`:
- constructor: `SlangSource(String source, String name) you can pass anything here explicitly
- `public static SlangSource fromFile(File file)`, `public static SlangSource fromFile(URI uri)`
  - name is taken as `remove_extension(fileName)`
- **CHANGED** `public static SlangSource fromBytes(byte[] bytes, String fileName)` - 
  - name is taken as `remove_extension(fileName)`
  - e.g. source = fromBytes(_, **my_flow.sl**) -> source(_, **my_flow**)

WDYT? @aeskin, @maayan-avraham
