### ISSUE TITLE
The pre-compile passes for navigate section that is parallel to the steps

### ISSUE THREAD

**Issue by meshipeer** [CloudSlang/cloud-slang#738]

**Comment by gituser173** [comment]
please add an example, more details on how to reproduce this bug

**Comment by meshipeer** [comment]
namespace: sgfg
flow:
  name: low2
  workflow:
    - flow1_1:
        navigate:
          - SUCCESS: 'NULL'
          - FAILURE: on_failure
        do:
          sgfg.flow1: []
     navigate:
        - SUCCESS: 'NULL'
        - FAILURE: on_failure

    - flow1:
        navigate:
          - SUCCESS: 'NULL'
          - FAILURE: on_failure
        do:
          sgfg.flow1: []
  results:
    - FAILURE
