### ISSUE TITLE
Test that run with success with builder (0.9.59.4) fails on CircleCI

### ISSUE THREAD

**Issue by andreeapuscas** [CloudSlang/cloud-slang#742]
The following test runs with success using the builder 0.9.59.4 but when I commit it on GitHub, the test failed on CircleCI.

testAttributesNotQuoted:
  inputs:
    - xml_document: '<?xml version="1.0" encoding="UTF-8"?>
                                                                        <bookstore>
                                                                          <book>
                                                                            <title lang="en">Harry Potter</title>
                                                                            <price>29.99</price>
                                                                          </book>
                                                                          <book>
                                                                            <title lang=en>Learning XML</title>
                                                                            <price>39.95</price>
                                                                          </book>
                                                                        </bookstore>'
  description:  "Tests that validate.sl operation finishes with FAILURE when attributes are not quoted"
  testFlowPath: io.cloudslang.base.xml.validate
  outputs:
    - return_result: 'Parsing error: Open quote is expected for attribute "lang" associated with an  element type  "title".'
    - result_text: "failure"
  result: FAILURE

Here is the error from circleci:
 ------------------------------------------------------------
09:57:56 [ERROR] BUILD FAILURE
09:57:56 [ERROR] ------------------------------------------------------------
09:57:56 [ERROR] CloudSlang build for repository: "/home/ubuntu/cloud-slang-content" failed due to failed tests.
09:57:56 [ERROR] Following 1 tests failed:
09:57:56 [ERROR] - Test case failed: testAttributesNotQuoted - Tests that validate.sl operation finishes with FAILURE when attributes are not quoted
		For output: return_result
		Expected value: Parsing error: Open quote is expected for attribute "lang" associated with an  element type  "title".
		Actual value: Parsing error: Open quote is expected for attribute "{1}" associated with an  element type  "lang".
09:57:56 [ERROR] 

case ${CIRCLE_NODE_INDEX} in 0) ./cslang-builder/bin/cslang-builder -ts default,jenkins,consul,http,rest,mail -cov ;; 1) ./cslang-builder/bin/cslang-builder -ts ${ACTIVE_CI_TEST_SUITES_DROPLETS_NODE_1} -cov ;; 2) ./cslang-builder/bin/cslang-builder -ts ${ACTIVE_CI_TEST_SUITES_DROPLETS_NODE_2} -cov ;; esac
 returned exit code 1

**Comment by Bonczidai** [comment]
behavior is different between the jdk's - since this is a 3'rd party implementation we must leave with it, Isuggest to align the error message to the jdk used on CIrcleCI
