### ISSUE TITLE
CloudSlang - change to case insenstive

### ISSUE THREAD

**Issue by maayan-avraham** [CloudSlang/cloud-slang#745]
System properties: CloudSlang is case sensitive 
Flows&Operations: it not been checked because the operating system is case insensitive. 

There is a need to change the behavior to be **case insensitive**, that mean that we need to block the option to add 2 system properties with the same name regardless to upper/lower case.
in addition, check the issue regarding flows & operation and block there too.

**Comment by Bonczidai** [comment]
details on the PR
