### ISSUE TITLE
Allow the creation of anonymous SlangSource objects from ad-hoc bytes

### ISSUE THREAD

**Issue by danfilip** [CloudSlang/cloud-slang#760]
Currently the cloudslang api validates if the filename of the SlangSource matches the name of the flow/operation defined inside the source.

Now it is impossible to precompile an ad-hoc stream of bytes without knowing the name inside the source, like this:
```java
        Executable exec = this.slangCompiler.preCompile(SlangSource.fromBytes(flowXml, "dummy.sl"));
```

It would be very useful for if the api would allow the creation of Anonymous Slang sources that will not validate the filename.

**Comment by meshipeer** [comment]
can i close this?
