### ISSUE TITLE
[FLOW} Using steps output as another steps input fails

### ISSUE THREAD

**Issue by barak-nagar** [CloudSlang/cloud-slang#776]
In the following flow we have two steps.
The first calls javaMulOfSum JAVA_Operation that receives two inputs and publish an output which is a number. the output is called "result".
On success we navigate to another operation called javaSumOfMul, which also receives two numbers and perform a calculation.
This operation ends with "SUCCESS" with any input but the "result" output of the previous step. Meaning, it will run with constant, expressions, sys props and flow inputs.
But when given the previous step result as an input it throws an exception with the message 
"Method [compute] invocation of class [utils.complex.Compute] failed!!!!"

The content pack that is used is (slang-versioning-cp-example.jar) can be found here:
https://irock.jiveon.com/servlet/JiveServlet/download/133939-11-73167/slang-versioning-cp-example.jar

#!!
#!!#
namespace: folder1
flow:
  name: barak
  inputs:
    - var1:
        default: '3'
    - var2
  workflow:
    - javaMulOfSum:
        do:
          user.versioning.math.ops.javaMulOfSum:
            - var1: '${var1}'
            - var2: '${var2}'
        publish:
          - result: '${result}'
        navigate:
          - SUCCESS: javaSumOfMul
    - javaSumOfMul:
        do:
          user.versioning.math.ops.javaSumOfMul:
            - var1: '${result}'
            - var2: '5'
        publish:
          - result2: '${result}'
        navigate:
          - SUCCESS: SUCCESS
  results:

**Comment by barak-nagar** [comment]
What happens is that the output of the first flow is a number (49)
It passes it as ${49} as input to the next step instead of '49' (it passes an expression)

**Comment by gituser173** [comment]
This is not a bug, you need to do `${str(result)}` for the var1 input for the javaSumOfMul step or do a similar expression in the inputs of the javaSumOfMul operation.
