### ISSUE TITLE
@Param should not be must for using java actions

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cloud-slang#807]
When referencing java actions with _GAV and class name and method name_ one seems to be bound to write the method in a particular manner - _using @Param_ - in order to make it work with CloudSlang.

This limitation should be removed and any java action should be runn-able from CloudSlang

> Caused by: java.lang.RuntimeException: All action arguments should be annotated with @Param
>             at io.cloudslang.lang.runtime.steps.CloudSlangJavaExecutionParameterProvider.getExecutionParameters(CloudSlangJavaExecutionParameterProvider.java:75)
>             at io.cloudslang.runtime.impl.java.JavaExecutor.execute(JavaExecutor.java:89)
>             ... 19 more
> 27/07/16 17:22:19 [ERROR] Error occurred during operation execution.

**Comment by meshipeer** [comment]
@andreivasiletruta - we need this for manipulate the inputs names
we can find work around to avoid it and use reflection - do you see this as something critical?

**Comment by andreivasiletruta** [comment]
@meshipeer: I am not seeing it as critical. It would be nice though. I would say just out of consistency if we go with @Param to keep @Action as a best practice too.
