### ISSUE TITLE
loadSystemProperties method validations don't match run time validations

### ISSUE THREAD

**Issue by maayan-avraham** [CloudSlang/cloud-slang#810]
loadSystemProperties method in SlangCompiler class don't match run time validations on name of system properties.
According to the regex used for get_sp the valid chars are alphanumeric and hyphen: [\w-].
first, there is a need to understand why are those limitations exist, do we really need to allow only those chars? and second to align it with slangCompiler.loadSystemProperties method. maybe there are more limitations on SP files (beside name of property) and we need to align those limitations too, with the SP file compilation

**Comment by barak-nagar** [comment]
Also a decision with no results or empty results is valid in re-compile and fails at runtime:

'{compare} syntax is invalid: 'results' section cannot be empty for executable type 'decision' 

Happans both to  no 'results:' section as well as with ' results: []'
