### ISSUE TITLE
Request: make LanguageEventData.getStepType more specific

### ISSUE THREAD

**Issue by aeskin** [CloudSlang/cloud-slang#811]
We have a defect in OO whereby in the table view of the run drilldown the icons denoting step types are not shown. The reason is that LanguageEventData.getStepType is not specific enough. For all of the following types: [operation, sub-flow, decision] it returns LanguageEventData.StepType#EXECUTABLE.

Can we replace StepType#EXECUTABLE by 3 other types: StepType#OPERATION, StepType#DECISION, StepType#FLOW? Or is there any other way to detect the exact step type?

**Comment by orius123** [comment]
it is not an issue, this is the design..
