### ISSUE TITLE
Characters convention

### ISSUE THREAD

**Issue by dumagalex** [CloudSlang/cloud-slang#817]
Characters convention in names of input/output & flow/operation/decision+instantiating steps

- **Which are the permitted / illegal characters in input/output names?** 

We should have a documented convention on this ( as for [namespaces (project & folder)](http://cloudslang-docs.readthedocs.io/en/v0.9.60/cloudslang_best_practices.html) and [system properties](https://github.com/CloudSlang/cloud-slang/pull/815) - \w-. )

A discussion was started in https://github.com/CloudSlang/docs/issues/212, but "In general, CloudSlang variable names must conform to both Python’s naming constraints as well as Java’s naming constraints." is not explicit for users/applications writing CS code.
     Does this mean only letters, digits and _ , starting with a letter ?
Also do we have a list of (java/python/yaml) keywords which are forbidden to use?

- The same problem should be clarified for the **names of results & flows,operation,decisions+the steps instantiating them**

**Comment by Bonczidai** [comment]
adding @andreeapuscas

**Comment by Bonczidai** [comment]
| Item | Valid chars | Documented | Validated in the code |
| :--------: |  :--------: |  :--------: |  :--------: | 
| values associated with variables | no restrictions, depends on the encoding used | ? | N/A |
|-|-|-|-|
| system property FQN | G1 | ? | yes |
| executable namespace | G1 | [Best practices](http://cloudslang-docs.readthedocs.io/en/v0.9.60/cloudslang_best_practices.html#cloudslang-content-best-practices) | no |
| import section values | G1 | ? | no |
| import section aliases | G1 | ? | no |
| executable name | G1 | ? | no |
| step name | G1 | ? | no |
| step reference | G1 | ? | no |
|-|-|-|-|
| result names | G2 | ? | no |
| navigation keys | G2 | ? | no |
| break keys | G2 | ? | no |
|-|-|-|-|
| input name | G3 | ? | no |
| output name | G3 | ? | no |
| publish keys | G3 | ? | no |
| loop statement variable | G3 | ? | no |

notes:
- executable in [flow, op, decision]
- `\w` includes `A a 9 _`

**We need to validate in the code and document explicitely the accepted characters**:
- G1: \w starting with letter or underscore
- G2: \w starting with letter or underscore
- G3 (variable names): \w starting with letter or underscore

For G1 and G2 it may be possible to add additional characters like white spaces - do you see such a need?

For G3 (Variable names) there also a list of reserved keywords (Java and Python). Later on we may add other scripting languages with its own keywords, change versions - so this set may change. DO you think we should validate these keywords?

**Comment by Bonczidai** [comment]
adding @CloudSlang/slang-functional-reviewers

**Comment by dumagalex** [comment]
We need to allow commas in the loop statement variable: key,value pairs are used for iterating through maps

**Comment by oritstone** [comment]
Sorry for the late input, but what about:
- Executable names that are the word: true or false or a number (4). Won't it be wrongly interpreted by CS compiler?
- Executable names which are reserved words in windows such as - COM1, PRN... It is impossible to create folders or files with these names in windows

Do we want to limit our legal words some more?

**Comment by Bonczidai** [comment]
- if you have `true.sl` and `name: true` in the flow it fails, but `name: 'true'` does not - what would be the expected behavior?
- well, the decision was not to limit keywords:
```
"For G3 (Variable names) there also a list of reserved keywords (Java and Python). Later on we may add other scripting languages with its own keywords, change versions - so this set may change. Do you think we should validate these keywords?
[Update] - not for now"
```

did we change this direction?

adding @meshipeer

**Comment by oritstone** [comment]
- I think that since `name: true` or `name: 3` fails compilation, we should document it as illegal names
- Regarding the reserved words for which we cannot create folders or files, do we want to document them as illegal?
- And what about system property name? Do we want to treat it as executable name (G1)?

**Comment by Bonczidai** [comment]
we decided to enhance documentation on the first two cases:
```
- I think that since name: true or name: 3 fails compilation, we should document it as illegal names
- Regarding the reserved words for which we cannot create folders or files, do we want to document them as illegal?
```
IMHO this list should also mention reserved keywords of Java and Python
https://github.com/CloudSlang/docs/issues/260

in the third case I think not, they seem to me logically different: SP name (namespace rules), exec name (simple name rules) -- right now the diff is that SP name can contain also dots, exec name cannot

**Comment by oritstone** [comment]
Also regarding step name - step name of `true` or `3` fails compilation, I think we should document it as illegal names as well

**Comment by SamMarkowitz** [comment]
@oritstone we currently have the following in the latest docs to cover those cases. 

```
Names that are interpreted by YAML as non-string types (e.g. booleans, numbers) cannot be used 
without enclosing them in quotes (') to force YAML to recognize them as strings.
```
