### ISSUE TITLE
Rebuilding process when merging or testing merged commits does not exit on failure

### ISSUE THREAD

**Issue by tethryus** [CloudSlang/cloud-slang#827]
When CircleCI and TravisCI run after a pull request is open or it has been merged and the build fails either because of network issues or other environment problems, it does not exit if the environment is not built correctly.

**Comment by Bonczidai** [comment]
opened an issue on CircleCi's side: https://discuss.circleci.com/t/build-should-stop-on-failed-setup-step/5976
