### ISSUE TITLE
CLI display message when starting/finished to download dependencies

### ISSUE THREAD

**Issue by tethryus** [CloudSlang/cloud-slang#846]
A nice feature, would be having a message that informs you that the CLI has started downloading the required dependencies and a SUCCESS or FAILURE message in case something goes wrong while downloading them.  It does not have to show the full message, with all the dependencies that are downloading, just something like "Download Maven dependencies, please wait ..." and after it finishes "Maven dependencies downloaded successfully". A Failure message appears, in case of a failure in downloading them.

**Comment by Bonczidai** [comment]
👍 for the informative / short console messages
