### ISSUE TITLE
Parallel loop iterator string list

### ISSUE THREAD

**Issue by eyalboas** [CloudSlang/cloud-slang#862]
in parallel loop when using list of string as the iterator it does not work
in loop it works
example:

namespace: aaaaa
flow:
  name: fatherflow2
  workflow:
    - rrrr:
        parallel_loop:
          for: "k in **'1,2,3'**"
          do:
            aaaaa.rrrr: []
        navigate:
          - FAILURE: on_failure
          - SUCCESS: SUCCESS
  results:
    - FAILURE
    - SUCCESS

**Comment by Bonczidai** [comment]
this one should be handled together with #839
