### ISSUE TITLE
pre compiler return empty string as dependency when the step reference contains Hebrew character

### ISSUE THREAD

**Issue by maayannoy** [CloudSlang/cloud-slang#863]
we have a defect in QC: 32093: Project Panel - Hebew - saving a flow with hebrew step in it gets error bad request (photos attached)

The problem is that when step contain reference with Hebrew character the preCompiler return executableDependencies with empty string instead of the real reference.

**Comment by Bonczidai** [comment]
According to #817 for `v1.0` we does not support foreign characters

**Comment by meshipeer** [comment]
we still need to return metadata + error in this case and not empty identifier...
