### ISSUE TITLE
Private inputs and outputs need to be different?

### ISSUE THREAD

**Issue by Bonczidai** [CloudSlang/cloud-slang#876]
? private inputs should not be considered here

**Comment by tethryus** [comment]
@Bonczidai The builder and CLI does throw an exception in case inputs and outputs are the same, which has been fixed? Is there any more testing to be done regarding this issue?

**Comment by Bonczidai** [comment]
the issue here is whether we should also consider private inputs in this validation - since they are NOT part of the interface I think we  should skip them

**Comment by Bonczidai** [comment]
reproduce: write an op with an private input and output with the same name - fails, should pass for private inputs
