### ISSUE TITLE
[Performance] Printing to console should be asynchronous to decrease builder time

### ISSUE THREAD

**Issue by lucian-cm** [CloudSlang/cloud-slang#903]
Currently we print to console and wait for that operation to finish before proceeding to doing different things like running a test case or compiling the next .sl or test case. 

#893 Console service addition will also help here.
This can improve builder test execution depending on the number of messages for this service.
Additionally flushes to console don't all have to be immediate reducing time even more.

**Comment by Bonczidai** [comment]
👍
