### ISSUE TITLE
Content format validation

### ISSUE THREAD

**Issue by tethryus** [CloudSlang/cloud-slang#944]
it would be a nice feature in the content validation of the .sl files to have the following:
- ###########################################################################
  before the YAML start tag
- ###########################################################################
  after the YAML end flag
- One newline between @description @input, @output @result

**Comment by Bonczidai** [comment]
👍 similar functionality to `org.apache.maven.plugins.maven-checkstyle-plugin` and `com.mycila.license-maven-plugin`

**Comment by lucian-cm** [comment]
@tethryus Good addition!
@Bonczidai @tethryus 
I think this must be included in both `CloudSlang CLI` and `CloudSlang builder`, but with high priority in the CloudSlang builder.
