### ISSUE TITLE
Parsing metadata fails all together

### ISSUE THREAD

**Issue by cid77** [CloudSlang/cloud-slang#960]
When processing the description of a flow, the parsing is stops immediately, therefor it's not possible to extract the valid elements.

E.g. having a bad flow input name

`#! @input flow_input_#2: description - details`

prevents extracting the description of the other inputs.

A more relaxed parsing approach, instead of the "all or nothing", would provide more flexibility.

**Comment by Bonczidai** [comment]
@gituser173 please have a look

**Comment by tethryus** [comment]
@bonczidai at the moment the builder fails after the first Metadata validation fails in the. sl file, whether it's an input output result. It would be a nice enhancement to have all errors caught for the same .sl file, although even in the currents state, it does provide a less error prone fix in case on multiple files.
