### ISSUE TITLE
Issue while defining number value in sl file

### ISSUE THREAD

**Issue by andreivasiletruta** [CloudSlang/cloud-slang#982]
_From @ranjith1976 on March 29, 2017 18:0_

I was trying the below sl through the java program it is failing saying that number is not allowed
operation:
-----------SL File----------
  name: print
  inputs:
    - text
    - value: "10"
  python_action:
    script: print value

  results:
    - WORKING: ${true}
    - FAILING
----------------SL File end --------------

Error is lke: Error occurred while executing flow [sample] java.lang.RuntimeException: For operation 'print' syntax is illegal. Input: 'value' should have a String value, but got value '10' of type Integer.

But this working from CLI console. What could be the reason? and what should i do to use run it via java program.

_Copied from original issue: CloudSlang/CloudSlang.github.io#197_

**Comment by andreivasiletruta** [comment]
@ranjith1976 did you try to str the value?
Where exactly are you running the code?

**Comment by Bonczidai** [comment]
@ranjith1976 what do you mean by `running with java` program` - how do you supply the inputs when you trigger? Be sure to submit string values

also, CloudSlang has a more detailed log, can you paste her the relevant section?
