### ISSUE TITLE
Error Message Not Clear : Command failed java.lang.RuntimeException: Slang Error: Failed to download resources using Mave

### ISSUE THREAD

**Issue by sbansal2507** [CloudSlang/cloud-slang#992]
I'm trying to Add new Java Action and calling it from the Operation but when I'm executing my workflow 
so always getting this problem.

My Project Structure is as below 

Project
 -src
   - com
      - abc
         - action
             - java action class
   - content
    - operation
        - operation java files
    - flow
        - flow files
 - test
 - pom.xml

Command:

run --f D:/ABC/Clones/Pratice/cloudslang/src/main/content/hiring/practice_java_action.sl --cp D:/ABC/Clones/Pratice/cloudslang/src/main/content

Configuration file

log4j.configuration=file:${app.home}/configuration/logging/log4j.properties
cslang.encoding=utf-8
maven.home=${app.home}/maven/apache-maven-3.3.9
maven.multiModuleProjectDirectory=${app.home}/maven/apache-maven-3.3.9
maven.settings.xml.path=${app.home}/maven/conf/settings.xml
maven.m2.conf.path=${app.home}/maven/conf/m2.conf
cloudslang.maven.repo.local=C:/Users/U51229/.m2/repository
cloudslang.maven.repo.remote.url=http://repo1.maven.org/maven2
cloudslang.maven.plugins.remote.url=http://repo1.maven.org/maven2

What should be directory structure for java files and contents.

Please help me to execute this case.

**Comment by andreivasiletruta** [comment]
@sbansal2507 I wonder if you have your action in the local repo above.

Feel free to jump on [gitter ](https://gitter.im/CloudSlang/cloud-slang?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)and you'll be able to discuss the problem there.
Feel free to jump on [slack ](https://cloudslang.signup.team/)too to stay up to date or discuss the problem there.

**Comment by Bonczidai** [comment]
furthermore, you can check the the execution.log under `<cli_dir>/logs` folder and maven specific logs under `<cli_dir>/logs/maven` folder

**Comment by sbansal2507** [comment]
Same message is there only...

**Comment by tethryus** [comment]
@andreivasiletruta @Bonczidai.  The issue has been fixed, it was related to the Maven version used. I`ve worked together with @sbansal2507 and got it to work. From what I can see, this issue can be closed, if there aren`t any other problems.

**Comment by Bonczidai** [comment]
great - closing the issue
