### ISSUE TITLE
SimpleValue object is not creatable

### ISSUE THREAD

**Issue by sbansal2507** [CloudSlang/cloud-slang#993]

**Comment by Bonczidai** [comment]
@sbansal2507 please share a bit more details

**Comment by sbansal2507** [comment]
slang.compileAndRun(CloudScore embedded ) requires input values map which is of String & Value to execute any flow or action. In my case, all values are simple string which means I have to create the SimpleValue object.

**Comment by Bonczidai** [comment]
that is true @sbansal2507 - the reason behind it is that CS works with `Value` wrapper for any runtime value (e.g. user inputs) so it can manage the sensitive data feature <- technical reasons.

You can use `ValueFactory` factory class to create the desired objects

**Comment by Bonczidai** [comment]
@sbansal2507 closing the issue for now - please reopen if you encounter further problems
